import { MethodologyStep } from '@/types/animation';

export const METHODOLOGY_PRESETS: Record<string, { name: string; description: string; steps: MethodologyStep[] }> = {
  all: {
    name: 'Full Delivery Methodology',
    description: 'The six phases every engagement moves through, from initial discovery to ongoing production support.',
    steps: [
      {
        id: 'step-1-discovery',
        stepNumber: 1,
        code: 'METH_01',
        title: 'Discovery & Product Definition',
        category: 'architecture',
        categoryLabel: 'Discovery & Design',
        subtitle: 'Requirements, domain mapping, and sprint planning',
        summary: 'We map how your business actually works before writing a line of code — domain boundaries, user flows, and a shared definition of what "done" looks like.',
        keyPractices: [
          'Structured workshops with the people who will actually use the system',
          'User stories and acceptance criteria written in plain, testable language',
          'Architecture decisions documented and agreed before any commitment to a schema',
          'A prioritized backlog with realistic sprint-by-sprint sequencing',
        ],
        deliverables: ['Requirements Document', 'Architecture Decision Log', 'Sprint Roadmap', 'API Specification'],
        techStack: ['Figma / Miro', 'OpenAPI', 'Jira / Linear'],
        kpis: [
          { label: 'Sprint Length', value: '2 Weeks' },
          { label: 'Requirements Sign-Off', value: 'Before Dev Starts' },
          { label: 'Scope Changes Post-Kickoff', value: 'Tracked & Estimated' },
        ],
        icon: 'Compass',
        phaseDuration: 'Phase 1 · Weeks 1–2',
        bestPractices: [
          'Keep engineering and product talking in the same language from day one',
          'Define clear system boundaries early to avoid a tangled, hard-to-change codebase',
          'Get sign-off on key technical decisions before they become expensive to reverse',
        ],
      },
      {
        id: 'step-2-frontend-mobile',
        stepNumber: 2,
        code: 'METH_02',
        title: 'Frontend & Interface Development',
        category: 'web',
        categoryLabel: 'Frontend & Mobile',
        subtitle: 'Responsive web interfaces and native-quality mobile apps',
        summary: 'We build interfaces that stay fast and consistent as the product grows, using a shared component system across web and mobile where it makes sense.',
        keyPractices: [
          'A reusable component library so new screens stay visually consistent',
          'Offline-friendly data handling on mobile, so a weak connection doesn\'t break the app',
          'Components built and tested in isolation before being wired into full pages',
          'Careful integration with device features (camera, location, biometrics) where needed',
        ],
        deliverables: ['Web Application', 'iOS / Android Builds', 'Component Library', 'State Management Layer'],
        techStack: ['React / Next.js', 'Flutter / React Native', 'Tailwind CSS'],
        kpis: [
          { label: 'Core Web Vitals', value: 'Passing' },
          { label: 'Target Frame Rate', value: '60 FPS' },
          { label: 'Initial Bundle Size', value: 'Budgeted & Monitored' },
        ],
        icon: 'Smartphone',
        phaseDuration: 'Phase 2 · Sprints 1–4',
        bestPractices: [
          'Set a performance budget up front rather than optimizing after the fact',
          'Build to WCAG accessibility standards from the start, not as a retrofit',
          'Use code-splitting so users only download what the current page needs',
        ],
      },
      {
        id: 'step-3-microservices-api',
        stepNumber: 3,
        code: 'METH_03',
        title: 'Backend Services & API Architecture',
        category: 'architecture',
        categoryLabel: 'Backend Core',
        subtitle: 'APIs, databases, and event-driven services',
        summary: 'We design backend systems sized to your actual scale — simple where simple is enough, distributed only where the load genuinely requires it.',
        keyPractices: [
          'Contract-first API design, so frontend and backend teams can work in parallel',
          'Clear data ownership per service, with proper indexing for the queries you actually run',
          'Asynchronous processing for anything that shouldn\'t block a user-facing request',
          'Authentication and rate-limiting built in from the first deployment, not bolted on later',
        ],
        deliverables: ['API Services', 'Database Schema & Migrations', 'Event Pipeline (where applicable)', 'Gateway Configuration'],
        techStack: ['Node.js / Go / .NET', 'PostgreSQL', 'Redis', 'Message Queue (Kafka / RabbitMQ)'],
        kpis: [
          { label: 'API Response Time (p95)', value: 'Under 200ms' },
          { label: 'Error Budget', value: 'Defined Per Service' },
          { label: 'Test Coverage on Core Paths', value: '80%+' },
        ],
        icon: 'Server',
        phaseDuration: 'Phase 3 · Sprints 2–6',
        bestPractices: [
          'Add retry and backoff logic on anything calling an external service',
          'Separate read-heavy and write-heavy workloads once traffic patterns justify it',
          'Automate schema migrations with a tested rollback path',
        ],
      },
      {
        id: 'step-4-tdd-qa',
        stepNumber: 4,
        code: 'METH_04',
        title: 'Quality Assurance & Testing',
        category: 'devops',
        categoryLabel: 'Quality Assurance',
        subtitle: 'Automated testing woven into every sprint, not bolted on at the end',
        summary: 'Testing runs continuously through development — unit, integration, and end-to-end — so issues surface while they\'re still cheap to fix.',
        keyPractices: [
          'Automated test suites run on every commit, before code reaches staging',
          'Cross-browser and cross-device end-to-end testing for critical user flows',
          'Contract testing between frontend and backend to catch integration breaks early',
          'A dedicated pre-launch pass covering load, security, and edge cases',
        ],
        deliverables: ['Automated Test Suite', 'Coverage Reports', 'End-to-End Test Results', 'Pre-Launch QA Report'],
        techStack: ['Vitest / Jest', 'Playwright', 'SonarQube'],
        kpis: [
          { label: 'Core Path Coverage', value: '80%+' },
          { label: 'Regression Suite', value: 'Runs Every Build' },
          { label: 'CI Pipeline Time', value: 'Under 10 mins' },
        ],
        icon: 'ShieldCheck',
        phaseDuration: 'Phase 4 · Continuous',
        bestPractices: [
          'Treat an unreliable ("flaky") test as a real defect, not background noise to ignore',
          'Mock third-party services at the boundary so tests stay fast and repeatable',
          'Run the full test matrix across the browsers and devices your users actually have',
        ],
      },
      {
        id: 'step-5-cicd-gitops',
        stepNumber: 5,
        code: 'METH_05',
        title: 'Deployment & Infrastructure Automation',
        category: 'devops',
        categoryLabel: 'DevOps & Cloud',
        subtitle: 'Automated, low-risk releases with a clear rollback path',
        summary: 'Deployments are automated and staged — never a manual, high-stakes event — so shipping changes stays routine instead of risky.',
        keyPractices: [
          'Infrastructure defined as code, so environments are reproducible and reviewable',
          'Containerized builds scanned for vulnerabilities before deployment',
          'Staged rollouts (staging → limited production → full release) instead of one big switch',
          'Automatic rollback triggers if error rates spike after a release',
        ],
        deliverables: ['Infrastructure-as-Code Modules', 'CI/CD Pipeline', 'Deployment Runbook', 'Rollback Procedure'],
        techStack: ['Kubernetes', 'Docker', 'Terraform', 'GitHub Actions'],
        kpis: [
          { label: 'Deployment Type', value: 'Automated, Staged' },
          { label: 'Typical Lead Time', value: 'Under 1 Day' },
          { label: 'Rollback', value: 'Automated on Error Spike' },
        ],
        icon: 'GitBranch',
        phaseDuration: 'Phase 5 · Continuous Delivery',
        bestPractices: [
          'Keep all environment configuration in version control, with secrets encrypted',
          'Require a passing CI run and a peer review before anything merges to main',
          'Test your disaster-recovery process before you actually need it',
        ],
      },
      {
        id: 'step-6-observability',
        stepNumber: 6,
        code: 'METH_06',
        title: 'Monitoring & Ongoing Support',
        category: 'devops',
        categoryLabel: 'Operations & Support',
        subtitle: 'Visibility into how the system behaves in the real world',
        summary: 'Once live, we track the health signals that actually matter and stay engaged to resolve issues quickly rather than handing over a system and disappearing.',
        keyPractices: [
          'Centralized logging and tracing across every service, not just the ones that fail loudly',
          'Dashboards built around the metrics your team will actually check',
          'Uptime monitoring from multiple regions, with alerts routed to the right person',
          'A documented runbook so incidents get resolved consistently, not improvised each time',
        ],
        deliverables: ['Monitoring Dashboards', 'Alerting Rules', 'Incident Runbooks', 'Monthly Health Report'],
        techStack: ['OpenTelemetry', 'Prometheus / Grafana', 'Sentry'],
        kpis: [
          { label: 'Target Uptime', value: '99.9%' },
          { label: 'Alert Routing', value: 'Automated' },
          { label: 'Post-Incident Review', value: 'Every Major Incident' },
        ],
        icon: 'Activity',
        phaseDuration: 'Phase 6 · Ongoing',
        bestPractices: [
          'Set realistic uptime and response-time targets per service, not one blanket number',
          'Let alerts fire on trends, not just hard thresholds, to catch problems earlier',
          'Run a blameless review after any incident so the same issue doesn\'t repeat',
        ],
      },
    ],
  },

  web: {
    name: 'Web Application Methodology',
    description: 'A four-phase methodology for modern, production-grade web applications — from design system to global deployment.',
    steps: [
      {
        id: 'web-1',
        stepNumber: 1,
        code: 'WEB_01',
        title: 'Design System & Component Architecture',
        category: 'web',
        categoryLabel: 'Design & Foundations',
        subtitle: 'A reusable, accessible component library',
        summary: 'We build a shared component system first, so every screen after it goes faster and stays visually consistent.',
        keyPractices: [
          'Design tokens shared between Figma and the codebase, so design and dev never drift apart',
          'Accessible component primitives built to WCAG 2.1 AA from the start',
          'Visual regression checks on every UI pull request, so nothing breaks silently',
        ],
        deliverables: ['Component Library', 'Design Token Reference', 'Storybook Documentation'],
        techStack: ['React', 'Tailwind CSS', 'Storybook', 'TypeScript'],
        kpis: [
          { label: 'Component Reuse', value: 'High, tracked over time' },
          { label: 'Accessibility Target', value: 'WCAG 2.1 AA' },
        ],
        icon: 'Layers',
        phaseDuration: 'Sprint 1',
        bestPractices: ['Reference semantic design tokens, never hardcoded colors, so theming stays consistent.'],
      },
      {
        id: 'web-2',
        stepNumber: 2,
        code: 'WEB_02',
        title: 'Application Architecture & Rendering',
        category: 'web',
        categoryLabel: 'Architecture & Engine',
        subtitle: 'Server rendering, data fetching, and state management',
        summary: 'We choose a rendering and data strategy sized to your product — fast initial loads, sensible caching, and state that stays predictable as features are added.',
        keyPractices: [
          'Server-side rendering for pages where load speed and SEO matter most',
          'Structured data-fetching with caching, so the same data isn\'t re-requested needlessly',
          'A single, predictable pattern for client-side state, agreed before the app grows complex',
        ],
        deliverables: ['Rendering Architecture', 'Data-Fetching Layer', 'State Management Setup'],
        techStack: ['Next.js', 'TanStack Query', 'Zustand'],
        kpis: [
          { label: 'First Contentful Paint', value: 'Under 1.5s target' },
          { label: 'Lighthouse Performance', value: '90+ target' },
        ],
        icon: 'Zap',
        phaseDuration: 'Sprints 2–3',
        bestPractices: ['Keep server-rendered sections focused and stream in the rest, rather than blocking on everything at once.'],
      },
      {
        id: 'web-3',
        stepNumber: 3,
        code: 'WEB_03',
        title: 'Testing & Performance Auditing',
        category: 'web',
        categoryLabel: 'Verification & QA',
        subtitle: 'Cross-browser testing and automated performance checks',
        summary: 'Every critical user flow — checkout, sign-up, core workflows — is covered by automated tests that run before code reaches production.',
        keyPractices: [
          'End-to-end tests across the major browsers your users actually use',
          'Bundle-size budgets, with alerts if a change pushes the app past them',
          'Automated performance audits on every pull request, not just before launch',
        ],
        deliverables: ['End-to-End Test Suite', 'Performance Audit Reports', 'Bundle Size Reports'],
        techStack: ['Playwright', 'Vitest', 'Lighthouse CI'],
        kpis: [
          { label: 'Critical Flow Coverage', value: '100%' },
          { label: 'Layout Shift (CLS)', value: 'Near zero, monitored' },
        ],
        icon: 'ShieldCheck',
        phaseDuration: 'Continuous',
        bestPractices: ['Run the full end-to-end suite on a preview deployment before every merge to production.'],
      },
      {
        id: 'web-4',
        stepNumber: 4,
        code: 'WEB_04',
        title: 'Deployment & Real-User Monitoring',
        category: 'web',
        categoryLabel: 'Deployment & Telemetry',
        subtitle: 'Global delivery, error tracking, and usage analytics',
        summary: 'We deploy through a global CDN for fast load times everywhere, then track real errors and real usage — not just synthetic test results.',
        keyPractices: [
          'Edge caching with sensible invalidation rules, so updates go live without a full cache wipe',
          'Error tracking that captures enough context to actually debug a production issue',
          'Privacy-respecting analytics focused on the funnels that matter to the business',
        ],
        deliverables: ['Deployment Pipeline', 'Error Monitoring Dashboard', 'Usage Analytics Setup'],
        techStack: ['Vercel / Cloudflare', 'Sentry', 'PostHog'],
        kpis: [
          { label: 'Global Load Time', value: 'CDN-backed, monitored' },
          { label: 'Error-Free Sessions', value: 'Tracked monthly' },
        ],
        icon: 'Activity',
        phaseDuration: 'Continuous Production',
        bestPractices: ['Set an automated alert if error rates cross a defined threshold after a release.'],
      },
    ],
  },

  mobile: {
    name: 'Mobile Application Methodology',
    description: 'A four-phase methodology covering cross-platform architecture, offline support, device testing, and app store delivery for iOS and Android.',
    steps: [
      {
        id: 'mob-1',
        stepNumber: 1,
        code: 'MOB_01',
        title: 'Platform Architecture',
        category: 'mobile',
        categoryLabel: 'Core Architecture',
        subtitle: 'Cross-platform foundation with native performance where it counts',
        summary: 'We decide honestly whether your app needs fully native development or whether a cross-platform framework gets you to market faster without a real trade-off.',
        keyPractices: [
          'Native modules for anything performance- or hardware-sensitive (camera, biometrics, GPS)',
          'Platform-appropriate design — iOS and Android conventions respected, not a single generic UI',
          'Shared business logic where it makes sense, native UI where it matters for feel',
        ],
        deliverables: ['App Architecture Document', 'Native Module Integrations', 'Design System (Mobile)'],
        techStack: ['React Native / Flutter', 'Swift', 'Kotlin'],
        kpis: [
          { label: 'Cold Start Time', value: 'Under 2s target' },
          { label: 'Target Frame Rate', value: '60 FPS' },
        ],
        icon: 'Smartphone',
        phaseDuration: 'Sprint 1–2',
        bestPractices: ['Keep heavy computation off the main UI thread so scrolling and animations stay smooth.'],
      },
      {
        id: 'mob-2',
        stepNumber: 2,
        code: 'MOB_02',
        title: 'Offline Support & Data Sync',
        category: 'mobile',
        categoryLabel: 'Data & State',
        subtitle: 'An app that keeps working on a bad connection',
        summary: 'For apps that need it, we build local-first storage with background sync, so a dropped connection doesn\'t mean a broken experience.',
        keyPractices: [
          'A local database that mirrors what the user needs, even fully offline',
          'Background sync that resolves conflicts sensibly when connectivity returns',
          'Optimistic UI updates, with a clear rollback if a sync ultimately fails',
        ],
        deliverables: ['Local Data Layer', 'Sync Engine', 'Offline Test Coverage'],
        techStack: ['SQLite', 'WatermelonDB', 'TanStack Query'],
        kpis: [
          { label: 'Core Features Usable Offline', value: 'Defined per project' },
          { label: 'Sync Conflict Handling', value: 'Tested & documented' },
        ],
        icon: 'Database',
        phaseDuration: 'Sprints 2–4',
        bestPractices: ['Store sensitive local data encrypted, even in an offline cache.'],
      },
      {
        id: 'mob-3',
        stepNumber: 3,
        code: 'MOB_03',
        title: 'Device Testing & QA',
        category: 'mobile',
        categoryLabel: 'Quality Assurance',
        subtitle: 'Real devices, real conditions, not just a simulator',
        summary: 'We test on a real spread of physical devices and OS versions, not just the newest flagship phone in a simulator.',
        keyPractices: [
          'Automated UI testing across core user flows on real device farms',
          'Testing across a meaningful range of screen sizes, OS versions, and network speeds',
          'Battery and memory profiling, especially for background-running features',
        ],
        deliverables: ['Device Test Matrix', 'Automated UI Test Suite', 'Performance Profiling Report'],
        techStack: ['Maestro / Detox', 'Firebase Test Lab'],
        kpis: [
          { label: 'Device Coverage', value: 'Range of models & OS versions' },
          { label: 'Crash-Free Sessions', value: 'Tracked post-release' },
        ],
        icon: 'ShieldCheck',
        phaseDuration: 'Sprints 3–5',
        bestPractices: ['Stress-test battery and data usage for any feature that runs in the background.'],
      },
      {
        id: 'mob-4',
        stepNumber: 4,
        code: 'MOB_04',
        title: 'Release & App Store Delivery',
        category: 'mobile',
        categoryLabel: 'Release & Distribution',
        subtitle: 'A controlled rollout, not a single risky release',
        summary: 'We automate the build and release process and roll out gradually, so a bad release affects a small slice of users, not everyone at once.',
        keyPractices: [
          'Automated build, signing, and submission pipeline for both app stores',
          'Internal testing distribution on every merge, before anything reaches real users',
          'Phased rollout with a defined crash-rate threshold that pauses the release automatically',
        ],
        deliverables: ['Release Pipeline', 'Internal Testing Builds', 'Store Listing & Metadata'],
        techStack: ['Fastlane', 'GitHub Actions', 'App Store Connect / Google Play Console'],
        kpis: [
          { label: 'Build Time', value: 'Automated, monitored' },
          { label: 'Rollout Strategy', value: 'Phased, with crash thresholds' },
        ],
        icon: 'GitBranch',
        phaseDuration: 'Continuous Release',
        bestPractices: ['Always roll out in stages so an unexpected issue is caught early, not at full scale.'],
      },
    ],
  },

  erp: {
    name: 'ERP & Enterprise Systems Methodology',
    description: 'A four-phase methodology for transactional enterprise platforms where data integrity, security, and uptime carry real business risk.',
    steps: [
      {
        id: 'erp-1',
        stepNumber: 1,
        code: 'ERP_01',
        title: 'Data Modeling & Architecture',
        category: 'architecture',
        categoryLabel: 'Data & Architecture',
        subtitle: 'A schema built for correctness first, scale second',
        summary: 'We design the data model around your actual business rules — accurate relationships and constraints, sized to grow without a redesign later.',
        keyPractices: [
          'Careful relational modeling with the constraints that keep financial and operational data correct',
          'Indexing and partitioning planned around the queries the business actually runs',
          'Multi-tenant data isolation where the system needs to serve more than one business unit or client',
        ],
        deliverables: ['Data Model Diagram', 'Migration Scripts', 'Indexing Plan'],
        techStack: ['PostgreSQL', 'Prisma / Drizzle', 'Redis'],
        kpis: [
          { label: 'Data Integrity Constraints', value: 'Enforced at the database level' },
          { label: 'Query Performance', value: 'Benchmarked pre-launch' },
        ],
        icon: 'Database',
        phaseDuration: 'Phase 1 · Foundations',
        bestPractices: ['Keep day-to-day transactional queries separate from heavy reporting queries so one doesn\'t slow down the other.'],
      },
      {
        id: 'erp-2',
        stepNumber: 2,
        code: 'ERP_02',
        title: 'Integration & Event Processing',
        category: 'architecture',
        categoryLabel: 'Integration & Workflow',
        subtitle: 'Connecting modules, legacy systems, and third parties reliably',
        summary: 'Most ERP work involves connecting to something that already exists. We build integrations that handle failures gracefully instead of silently losing data.',
        keyPractices: [
          'Event-driven processing for anything that shouldn\'t block a user waiting on a response',
          'Clear compensation logic for multi-step transactions that fail partway through',
          'Retry and dead-letter handling, so a temporary failure doesn\'t become a permanent data gap',
        ],
        deliverables: ['Integration Layer', 'Event Processing Pipeline', 'Failure-Handling Documentation'],
        techStack: ['Apache Kafka / RabbitMQ', 'Node.js / .NET / Go'],
        kpis: [
          { label: 'Message Delivery', value: 'At-least-once, with dedup' },
          { label: 'Failed Transaction Handling', value: 'Documented & tested' },
        ],
        icon: 'Server',
        phaseDuration: 'Phase 2 · Core Engine',
        bestPractices: ['Design consumers to be safely re-run, so a retried message never double-processes.'],
      },
      {
        id: 'erp-3',
        stepNumber: 3,
        code: 'ERP_03',
        title: 'Security, Access Control & Compliance',
        category: 'devops',
        categoryLabel: 'Security & Access',
        subtitle: 'Role-based access and a complete audit trail',
        summary: 'Enterprise systems need to prove who did what, when. We build role-based permissions and audit logging in from the start, not as an afterthought.',
        keyPractices: [
          'Single sign-on integration with your existing identity provider',
          'Granular, role-based access control mapped to your actual org structure',
          'An append-only audit log covering every meaningful state change in the system',
        ],
        deliverables: ['Access Control Configuration', 'Audit Log Schema', 'Compliance Documentation'],
        techStack: ['Okta / Azure AD / Keycloak', 'Vault'],
        kpis: [
          { label: 'Audit Trail Coverage', value: 'All state-changing actions' },
          { label: 'Access Control Model', value: 'Role-based, documented' },
        ],
        icon: 'ShieldCheck',
        phaseDuration: 'Phase 3 · Compliance',
        bestPractices: ['Store credentials and API keys in a dedicated secrets manager, never in application code or config files.'],
      },
      {
        id: 'erp-4',
        stepNumber: 4,
        code: 'ERP_04',
        title: 'High Availability & Disaster Recovery',
        category: 'devops',
        categoryLabel: 'Operations & SRE',
        subtitle: 'Built to stay up, and to recover fast if it doesn\'t',
        summary: 'For systems the business genuinely can\'t afford to lose, we plan for failure explicitly — clustering, backups, and a tested recovery process.',
        keyPractices: [
          'Automated database failover, so a single node issue doesn\'t become an outage',
          'Regular backups with a recovery process that\'s actually been tested, not just assumed to work',
          'Clear recovery time and recovery point targets agreed with you up front',
        ],
        deliverables: ['High-Availability Configuration', 'Disaster Recovery Runbook', 'Backup & Restore Schedule'],
        techStack: ['Kubernetes', 'Terraform', 'Prometheus'],
        kpis: [
          { label: 'Uptime Target', value: 'Agreed per project (e.g. 99.9%)' },
          { label: 'Recovery Point Objective', value: 'Defined & tested' },
        ],
        icon: 'Activity',
        phaseDuration: 'Phase 4 · Live Operations',
        bestPractices: ['Run a disaster-recovery drill on a schedule, not just once at launch.'],
      },
    ],
  },

  custom: {
    name: 'Custom Software Methodology',
    description: 'A four-phase methodology for purpose-built systems and high-performance workloads that off-the-shelf software can\'t handle.',
    steps: [
      {
        id: 'cust-1',
        stepNumber: 1,
        code: 'CUST_01',
        title: 'Core Architecture & Performance Design',
        category: 'architecture',
        categoryLabel: 'Core Foundations',
        subtitle: 'Built for the specific problem, not a generic template',
        summary: 'We start by understanding exactly what the system needs to handle — throughput, latency, memory constraints — and design accordingly rather than defaulting to an off-the-shelf pattern.',
        keyPractices: [
          'Architecture decisions grounded in your actual performance and scale requirements',
          'Early benchmarking of the riskiest technical assumptions, before committing to a full build',
          'Clean separation between core business logic and infrastructure, so either can change independently',
        ],
        deliverables: ['Architecture Specification', 'Performance Benchmark Report', 'Technical Risk Assessment'],
        techStack: ['Go / Rust / Python', 'C++ (where applicable)'],
        kpis: [
          { label: 'Key Assumptions', value: 'Benchmarked early' },
          { label: 'Performance Target', value: 'Defined per use case' },
        ],
        icon: 'Zap',
        phaseDuration: 'Phase 1 · Core Engine',
        bestPractices: ['Benchmark before optimizing — measure the actual bottleneck rather than guessing.'],
      },
      {
        id: 'cust-2',
        stepNumber: 2,
        code: 'CUST_02',
        title: 'Communication & Data Protocols',
        category: 'architecture',
        categoryLabel: 'Protocols & APIs',
        subtitle: 'Efficient, reliable communication between services',
        summary: 'For systems with real throughput or real-time requirements, we choose protocols and serialization formats that fit the load, not just whatever\'s convenient.',
        keyPractices: [
          'Contract-locked API definitions that both sides of an integration can rely on',
          'Streaming or real-time protocols where a request/response model would be too slow',
          'Backpressure handling, so a slow consumer doesn\'t bring down the whole pipeline',
        ],
        deliverables: ['API / Protocol Definitions', 'Client Libraries', 'Integration Test Suite'],
        techStack: ['gRPC / WebSockets', 'Protocol Buffers'],
        kpis: [
          { label: 'Protocol Choice', value: 'Matched to load pattern' },
          { label: 'Backpressure Handling', value: 'Tested under load' },
        ],
        icon: 'Server',
        phaseDuration: 'Phase 2 · Networking',
        bestPractices: ['Design every consumer to handle backpressure gracefully rather than assuming infinite capacity.'],
      },
      {
        id: 'cust-3',
        stepNumber: 3,
        code: 'CUST_03',
        title: 'Load Testing & Resilience',
        category: 'devops',
        categoryLabel: 'Resilience & QA',
        subtitle: 'Proving it holds up before it matters',
        summary: 'We test the system under realistic and worst-case load before launch — not just happy-path scenarios — so failure modes are known quantities, not surprises.',
        keyPractices: [
          'Load testing that simulates real traffic patterns, including sudden spikes',
          'Fault injection to confirm the system degrades gracefully rather than failing completely',
          'Edge-case and fuzz testing on anything that parses external input',
        ],
        deliverables: ['Load Test Results', 'Failure Mode Report', 'Resilience Test Suite'],
        techStack: ['k6', 'Chaos engineering tooling'],
        kpis: [
          { label: 'Load Test Coverage', value: 'Peak & sustained scenarios' },
          { label: 'Failure Recovery', value: 'Tested, not assumed' },
        ],
        icon: 'ShieldCheck',
        phaseDuration: 'Phase 3 · Verification',
        bestPractices: ['Run resilience testing continuously in staging, not as a one-time pre-launch checkbox.'],
      },
      {
        id: 'cust-4',
        stepNumber: 4,
        code: 'CUST_04',
        title: 'Deployment & Operational Visibility',
        category: 'devops',
        categoryLabel: 'Deployment & SRE',
        subtitle: 'Deployed with full visibility into how it actually behaves',
        summary: 'Custom systems need custom observability — we instrument what actually matters for this system, not a generic dashboard template.',
        keyPractices: [
          'Declarative infrastructure, so environments are reproducible and changes are reviewable',
          'Deep tracing at the level the system actually needs (including kernel-level, for latency-critical systems)',
          'Canary releases with automated rollback if key metrics move in the wrong direction',
        ],
        deliverables: ['Deployment Configuration', 'Observability Dashboards', 'Rollback Procedure'],
        techStack: ['Kubernetes', 'Prometheus / Grafana', 'ArgoCD'],
        kpis: [
          { label: 'Deployment Strategy', value: 'Canary, with auto-rollback' },
          { label: 'Observability Coverage', value: 'Matched to system criticality' },
        ],
        icon: 'GitBranch',
        phaseDuration: 'Phase 4 · Operations',
        bestPractices: ['Instrument for the failure modes this specific system is actually likely to hit, not a generic checklist.'],
      },
    ],
  },
};