import { MethodologyStep } from '@/types/animation';

export const METHODOLOGY_PRESETS: Record<string, { name: string; description: string; steps: MethodologyStep[] }> = {
  all: {
    name: 'Full-Lifecycle Engineering Matrix',
    description: 'Comprehensive 6-tier software engineering methodology covering product definition through cloud observability.',
    steps: [
      {
        id: 'step-1-discovery',
        stepNumber: 1,
        code: 'METH_01',
        title: 'Agile Discovery & Domain Modeling',
        category: 'architecture',
        categoryLabel: 'Discovery & Design',
        subtitle: 'Domain-Driven Design (DDD) & Event Storming',
        summary: 'Establish product scope, domain boundaries, bounded contexts, and user story maps with bi-weekly sprint cadence.',
        keyPractices: [
          'Event storming workshops to map core business domain models',
          'Epics, user stories, and acceptance criteria with Gherkin BDD syntax',
          'Architecture Decision Records (ADRs) to document key structural choices',
          'Sprint backlog grooming and velocity calibration metrics',
        ],
        deliverables: ['Domain Model Graph', 'ADR Repository', 'Jira Sprint Backlog', 'OpenAPI v3 Spec'],
        techStack: ['TypeScript', 'GraphQL Schema', 'Miro', 'OpenAPI', 'Jira / Linear'],
        kpis: [
          { label: 'Sprint Cycle', value: '2 Weeks' },
          { label: 'Story Ready SLA', value: '100%' },
          { label: 'Scope Clarity', value: '98.4%' },
        ],
        icon: 'Compass',
        phaseDuration: 'Phase 1 • Days 1–14',
        bestPractices: [
          'Ensure ubiquitous language between engineering and product teams',
          'Define strict boundary contexts to prevent monolithic coupling early',
          'Enforce peer-reviewed ADRs before any core database schema commitment',
        ],
      },
      {
        id: 'step-2-frontend-mobile',
        stepNumber: 2,
        code: 'METH_02',
        title: 'Modern Web & Cross-Platform Mobile',
        category: 'web',
        categoryLabel: 'Frontend & Mobile',
        subtitle: 'Microfrontends, React 19 & Flutter/React Native',
        summary: 'Deliver responsive high-fps web interfaces and offline-first mobile apps powered by shared state machines and atomic design.',
        keyPractices: [
          'Design tokens synchronized between Figma and Tailwind CSS',
          'Offline-first synchronization with optimistic local SQLite / IndexedDB',
          'Component-driven UI architecture with Storybook isolation testing',
          'Native hardware bridge optimization (Biometrics, Camera, Geolocation)',
        ],
        deliverables: ['Web PWA Application', 'iOS / Android Binaries', 'Storybook Design System', 'State Machine Schema'],
        techStack: ['React 19', 'Next.js / Vite', 'Flutter', 'React Native', 'Tailwind CSS'],
        kpis: [
          { label: 'Core Web Vitals', value: '99/100' },
          { label: 'Frame Rate', value: '60-120 FPS' },
          { label: 'Bundle Size', value: '< 180 KB' },
        ],
        icon: 'Smartphone',
        phaseDuration: 'Phase 2 • Sprints 1–4',
        bestPractices: [
          'Implement virtualized lists and memoized selectors for seamless scroll performance',
          'Ensure dark/light theme tokens and WCAG 2.1 AA accessibility compliance',
          'Utilize code-splitting and progressive image hydration',
        ],
      },
      {
        id: 'step-3-microservices-api',
        stepNumber: 3,
        code: 'METH_03',
        title: 'Cloud-Native APIs & Event Streaming',
        category: 'architecture',
        categoryLabel: 'Backend Core',
        subtitle: 'gRPC, Node/Go Microservices & Kafka Events',
        summary: 'Build low-latency asynchronous microservices with contract-first gRPC/REST endpoints and resilient event brokers.',
        keyPractices: [
          'Schema registry validation on all published Kafka/RabbitMQ events',
          'Distributed transaction handling with Saga pattern and compensation routines',
          'Database per service with connection pooling and query indexing',
          'Zero-trust mTLS authentication and rate-limiting gateway proxies',
        ],
        deliverables: ['Microservice Cluster', 'Kafka Topics & Consumers', 'API Gateway Config', 'Database Migrations'],
        techStack: ['Node.js / Go', 'PostgreSQL', 'Redis Cluster', 'Apache Kafka', 'gRPC / Envoy'],
        kpis: [
          { label: 'API P99 Latency', value: '< 28ms' },
          { label: 'Throughput', value: '45k req/s' },
          { label: 'Fault Tolerance', value: '99.99%' },
        ],
        icon: 'Server',
        phaseDuration: 'Phase 3 • Sprints 2–6',
        bestPractices: [
          'Apply circuit breakers and exponential backoff retry policies on all external I/O',
          'Isolate read and write paths using CQRS (Command Query Responsibility Segregation)',
          'Automate database schema migrations with zero-downtime rollback checks',
        ],
      },
      {
        id: 'step-4-tdd-qa',
        stepNumber: 4,
        code: 'METH_04',
        title: 'Shift-Left QA & Automated TDD',
        category: 'devops',
        categoryLabel: 'Quality Assurance',
        subtitle: 'Unit, Integration, E2E & Chaos Engineering',
        summary: 'Enforce stringent quality gates with automated test suites running on every branch commit before staging deployments.',
        keyPractices: [
          'Test-Driven Development (TDD) cycle: Red -> Green -> Refactor',
          'Headless browser E2E regression pipelines via Playwright / Cypress',
          'Contract verification between frontend clients and backend APIs via Pact',
          'Fuzz testing and Chaos Mesh failure injection on staging clusters',
        ],
        deliverables: ['Automated Test Suite', 'Code Coverage Reports', 'E2E Test Artifacts', 'Security Audit Logs'],
        techStack: ['Vitest / Jest', 'Playwright', 'Pact Contract Tests', 'SonarQube', 'Chaos Mesh'],
        kpis: [
          { label: 'Code Coverage', value: '92.4%' },
          { label: 'Regression Pass Rate', value: '100%' },
          { label: 'Pipeline Speed', value: '3.8 mins' },
        ],
        icon: 'ShieldCheck',
        phaseDuration: 'Phase 4 • Continuous Guardrails',
        bestPractices: [
          'Treat flaky tests as blocking defects and isolate non-deterministic fixtures',
          'Mock third-party gateways at the transport boundary to ensure reproducible builds',
          'Run parallel test matrices across multiple browser engines and mobile viewports',
        ],
      },
      {
        id: 'step-5-cicd-gitops',
        stepNumber: 5,
        code: 'METH_05',
        title: 'CI/CD Automation & GitOps Deployments',
        category: 'devops',
        categoryLabel: 'DevOps & Cloud',
        subtitle: 'Kubernetes, Terraform & ArgoCD Pipelines',
        summary: 'Achieve friction-free zero-downtime deployments with immutable infrastructure-as-code and blue/green canary rollouts.',
        keyPractices: [
          'Declarative infrastructure provisioning with Terraform and OpenTofu',
          'Containerized image signing with Cosign and vulnerability scanning with Trivy',
          'ArgoCD GitOps synchronization reconciling Kubernetes cluster state',
          'Canary deployments with automated rollback on error rate spikes (>0.1%)',
        ],
        deliverables: ['Terraform Modules', 'ArgoCD Applications', 'Helm Charts', 'Canary Rollout Rules'],
        techStack: ['Kubernetes (EKS/GKE)', 'Docker / Containerd', 'ArgoCD', 'Terraform', 'GitHub Actions'],
        kpis: [
          { label: 'Deploy Frequency', value: '18 / Day' },
          { label: 'Lead Time for Changes', value: '< 20 mins' },
          { label: 'Change Failure Rate', value: '< 0.5%' },
        ],
        icon: 'GitBranch',
        phaseDuration: 'Phase 5 • Continuous Delivery',
        bestPractices: [
          'Store all environment configs in version control with sealed encrypted secrets',
          'Automate multi-region failover and horizontal pod autoscaling (HPA)',
          'Enforce branch protection requiring dual senior approvals and passing CI audits',
        ],
      },
      {
        id: 'step-6-observability',
        stepNumber: 6,
        code: 'METH_06',
        title: 'Full-Stack Observability & SRE Runbooks',
        category: 'devops',
        categoryLabel: 'Operations & SRE',
        subtitle: 'OpenTelemetry, Prometheus, Grafana & Incident SLA',
        summary: 'Monitor health, trace end-to-end request latencies, and automate remediation with comprehensive SRE telemetry.',
        keyPractices: [
          'Distributed request tracing from browser click to database query via OpenTelemetry',
          'Prometheus metrics collection with Grafana golden signal dashboards',
          'Synthetic uptime probes evaluating geographic availability every 30 seconds',
          'Automated PagerDuty escalation policies with detailed runbook run-sheets',
        ],
        deliverables: ['Grafana Dashboards', 'OpenTelemetry Exporters', 'Alertmanager Rules', 'SRE Incident Runbooks'],
        techStack: ['OpenTelemetry', 'Prometheus', 'Grafana', 'Datadog', 'PagerDuty'],
        kpis: [
          { label: 'MTTR (Mean Time to Repair)', value: '< 4.2 mins' },
          { label: 'System Uptime', value: '99.999%' },
          { label: 'Trace Ingestion', value: '100% Core' },
        ],
        icon: 'Activity',
        phaseDuration: 'Phase 6 • 24/7 SRE Lifecycle',
        bestPractices: [
          'Define Service Level Objectives (SLOs) and error budgets for every microservice',
          'Trigger auto-scaling events based on CPU, memory, and queue depth pressure',
          'Conduct blameless post-mortems for any production incident lasting > 2 minutes',
        ],
      },
    ],
  },

  web: {
    name: 'Modern Web Application Methodology',
    description: '4-step high-velocity methodology tailored for modern React, Next.js, and Cloudflare Edge web applications.',
    steps: [
      {
        id: 'web-1',
        stepNumber: 1,
        code: 'WEB_01',
        title: 'Design System & Component Architecture',
        category: 'web',
        categoryLabel: 'Design & Foundations',
        subtitle: 'Atomic Design, Figma Tokens & Tailwind CSS',
        summary: 'Construct a reusable component system with accessible primitives, dark/light token matrices, and Storybook documentation.',
        keyPractices: [
          'Figma-to-Code token sync with CSS custom properties and Tailwind CSS utilities',
          'Headless component primitives (Radix UI / React Aria) ensuring WCAG 2.1 AA compliance',
          'Visual regression testing with Chromatic on all UI library pull requests',
        ],
        deliverables: ['Component UI Kit', 'Figma Token Map', 'Storybook Catalog'],
        techStack: ['React 19', 'Tailwind CSS', 'Radix UI', 'Storybook', 'TypeScript'],
        kpis: [
          { label: 'Component Reusability', value: '88%' },
          { label: 'Accessibility Score', value: '100/100' },
        ],
        icon: 'Layers',
        phaseDuration: 'Sprint 1',
        bestPractices: ['Avoid hardcoded color codes; always reference semantic theme tokens.'],
      },
      {
        id: 'web-2',
        stepNumber: 2,
        code: 'WEB_02',
        title: 'State Management & Edge SSR Rendering',
        category: 'web',
        categoryLabel: 'Architecture & Engine',
        subtitle: 'Server Components, Zustand & TanStack Query',
        summary: 'Implement hybrid streaming server-side rendering (SSR), optimistic UI updates, and intelligent caching at edge POP locations.',
        keyPractices: [
          'React Server Components (RSC) to minimize client-side JavaScript payloads',
          'TanStack Query for server state caching, background deduplication, and refetching',
          'Zustand store for deterministic client-side UI application state',
        ],
        deliverables: ['Edge SSR Middleware', 'Hydration Pipeline', 'API Data Hooks'],
        techStack: ['Next.js / Vite', 'TanStack Query', 'Zustand', 'Cloudflare Workers'],
        kpis: [
          { label: 'First Contentful Paint', value: '0.42s' },
          { label: 'Lighthouse Performance', value: '98/100' },
        ],
        icon: 'Zap',
        phaseDuration: 'Sprints 2–3',
        bestPractices: ['Keep server component boundaries shallow and stream critical UI instantly.'],
      },
      {
        id: 'web-3',
        stepNumber: 3,
        code: 'WEB_03',
        title: 'E2E Testing & Performance Profiling',
        category: 'web',
        categoryLabel: 'Verification & QA',
        subtitle: 'Playwright, Lighthouse CI & Web Vitals',
        summary: 'Execute cross-browser end-to-end regression suites and automated Web Vitals auditing in CI pipelines.',
        keyPractices: [
          'Parallel Playwright test runs across Chromium, WebKit, and Firefox',
          'Bundle size budgets with automated PR alerts when bundle expands > 5KB',
          'Synthetic user journeys verifying checkout, auth, and critical workflows',
        ],
        deliverables: ['Playwright Test Suite', 'Lighthouse CI Reports', 'Performance Audits'],
        techStack: ['Playwright', 'Vitest', 'Lighthouse CI', 'Bundle Analyzer'],
        kpis: [
          { label: 'Test Pass Rate', value: '99.8%' },
          { label: 'Cumulative Layout Shift', value: '0.00' },
        ],
        icon: 'ShieldCheck',
        phaseDuration: 'Continuous',
        bestPractices: ['Run E2E suites on ephemeral preview staging environments before merge.'],
      },
      {
        id: 'web-4',
        stepNumber: 4,
        code: 'WEB_04',
        title: 'Global Edge CDN Deployment & Analytics',
        category: 'web',
        categoryLabel: 'Deployment & Telemetry',
        subtitle: 'Edge Routing, Sentry Monitoring & Real User Metrics',
        summary: 'Deploy across 300+ global edge locations with instant cache invalidation, real-time error tracking, and user analytics.',
        keyPractices: [
          'Edge caching rules with stale-while-revalidate headers',
          'Sentry error instrumentation capturing stack traces and breadcrumbs',
          'Privacy-first analytics tracking feature usage and conversion funnels',
        ],
        deliverables: ['Edge Deployment Pipeline', 'Sentry Dashboard', 'Analytics Funnels'],
        techStack: ['Cloudflare / Vercel', 'Sentry', 'PostHog', 'OpenTelemetry'],
        kpis: [
          { label: 'Global Edge TTFB', value: '< 35ms' },
          { label: 'Error-Free Sessions', value: '99.94%' },
        ],
        icon: 'Activity',
        phaseDuration: 'Continuous Production',
        bestPractices: ['Implement automated edge rollback rules if error rate exceeds 0.05%.'],
      },
    ],
  },

  mobile: {
    name: 'Mobile Application Lifecycle (iOS & Android)',
    description: '4-step mobile engineering methodology covering cross-platform architecture, offline data synchronization, automated test flight builds, and app store delivery.',
    steps: [
      {
        id: 'mob-1',
        stepNumber: 1,
        code: 'MOB_01',
        title: 'Native Architecture & Bridge Optimization',
        category: 'mobile',
        categoryLabel: 'Core Architecture',
        subtitle: 'React Native New Arch / Flutter Engine & Native Modules',
        summary: 'Structure cross-platform applications with turbo modules, native rendering thread separation, and shared type definitions.',
        keyPractices: [
          'Fabric rendering engine and TurboModules for direct C++ JSI communication',
          'Native hardware integration (Biometrics, Push Notifications, Camera, GPS)',
          'Platform-specific styling adaptations for iOS Human Interface & Material 3',
        ],
        deliverables: ['React Native / Flutter Boilerplate', 'Native Bridge Bindings', 'Theme Configuration'],
        techStack: ['React Native', 'Flutter', 'Kotlin', 'Swift', 'TypeScript'],
        kpis: [
          { label: 'Launch Time (Cold)', value: '< 1.1s' },
          { label: 'UI Thread FPS', value: '60 / 120 FPS' },
        ],
        icon: 'Smartphone',
        phaseDuration: 'Sprint 1–2',
        bestPractices: ['Avoid bridging heavy computations to the JS thread; use native worker threads.'],
      },
      {
        id: 'mob-2',
        stepNumber: 2,
        code: 'MOB_02',
        title: 'Offline-First Storage & CRDT Conflict Sync',
        category: 'mobile',
        categoryLabel: 'Data & State',
        subtitle: 'WatermelonDB, SQLite & Background Sync Queues',
        summary: 'Enable full app functionality without internet connectivity using embedded SQLite and conflict-free replicated data types.',
        keyPractices: [
          'Embedded local database with indexed relational schema',
          'Background synchronization task queues executing when network restores',
          'Optimistic mutations with immediate UI reflection and rollback handling',
        ],
        deliverables: ['Local Database Schema', 'Sync Engine Queue', 'Offline Test Matrix'],
        techStack: ['WatermelonDB', 'SQLite', 'MMKV Storage', 'TanStack Query'],
        kpis: [
          { label: 'Offline Usability', value: '100%' },
          { label: 'Sync Resolution Latency', value: '< 120ms' },
        ],
        icon: 'Database',
        phaseDuration: 'Sprints 2–4',
        bestPractices: ['Always store critical user drafts in encrypted MMKV key-value caches.'],
      },
      {
        id: 'mob-3',
        stepNumber: 3,
        code: 'MOB_03',
        title: 'Device Matrix Testing & Detox Automation',
        category: 'mobile',
        categoryLabel: 'Quality Assurance',
        subtitle: 'Detox, Appium, Maestro & Device Cloud Testing',
        summary: 'Automate gray-box testing on real physical device clouds across multiple screen densities, OS versions, and network speeds.',
        keyPractices: [
          'Maestro / Detox UI automation for end-to-end user flows',
          'AWS Device Farm / Firebase Test Lab runs on 50+ real iOS and Android devices',
          'Memory leak and battery consumption profiling with Xcode Instruments & Android Studio Profiler',
        ],
        deliverables: ['E2E Test Suites', 'Device Farm Test Matrix', 'Memory Profiling Reports'],
        techStack: ['Maestro', 'Detox', 'Firebase Test Lab', 'Xcode Instruments'],
        kpis: [
          { label: 'Crash-Free Users', value: '99.95%' },
          { label: 'Device Coverage', value: '98.5%' },
        ],
        icon: 'ShieldCheck',
        phaseDuration: 'Sprints 3–5',
        bestPractices: ['Run battery consumption stress tests during background geolocation and sync operations.'],
      },
      {
        id: 'mob-4',
        stepNumber: 4,
        code: 'MOB_04',
        title: 'Fastlane CI/CD, TestFlight & App Store Release',
        category: 'mobile',
        categoryLabel: 'Release & Distribution',
        subtitle: 'Fastlane, App Store Connect & Google Play Phased Rollout',
        summary: 'Automate code signing, binary compilation, screenshot generation, and staged 10% -> 100% production rollout.',
        keyPractices: [
          'Fastlane automation for provisioning profiles, certificates, and build increments',
          'Automated TestFlight & Google Play Internal testing distributions on every merge',
          'Phased release cadence over 7 days with crash threshold circuit breakers',
        ],
        deliverables: ['Fastlane Match Repository', 'TestFlight Build Pipelines', 'App Store Metadata'],
        techStack: ['Fastlane', 'GitHub Actions', 'App Store Connect API', 'Google Play Developer API'],
        kpis: [
          { label: 'Build Time', value: '< 14 mins' },
          { label: 'Release Cadence', value: 'Weekly' },
        ],
        icon: 'GitBranch',
        phaseDuration: 'Continuous Release',
        bestPractices: ['Always utilize staged phased rollouts to catch unexpected edge cases before full audience exposure.'],
      },
    ],
  },

  erp: {
    name: 'Enterprise ERP & Distributed Systems Methodology',
    description: '4-step robust engineering lifecycle for transactional enterprise resource platforms, transactional ledgers, and distributed database partitions.',
    steps: [
      {
        id: 'erp-1',
        stepNumber: 1,
        code: 'ERP_01',
        title: 'Domain Modeling & Relational Partitioning',
        category: 'architecture',
        categoryLabel: 'Data & Architecture',
        subtitle: 'PostgreSQL Partitioning, Sharding & ACID Schemas',
        summary: 'Architect strict ACID relational schemas with horizontal partitioning, multi-tenant row security, and indexing strategies.',
        keyPractices: [
          'Declarative schema migrations with zero-downtime rollback checks',
          'PostgreSQL table partitioning and composite indexing for high-volume ledger queries',
          'Row-Level Security (RLS) enforcement isolating multi-tenant enterprise data',
        ],
        deliverables: ['ERD Schema Graph', 'Migration Scripts', 'Indexing Benchmark Report'],
        techStack: ['PostgreSQL', 'Prisma / Drizzle', 'TimescaleDB', 'Redis'],
        kpis: [
          { label: 'Query P95 Latency', value: '< 12ms' },
          { label: 'ACID Integrity', value: '100%' },
        ],
        icon: 'Database',
        phaseDuration: 'Phase 1 • Foundations',
        bestPractices: ['Isolate OLTP transactional loads from OLAP analytics workloads.'],
      },
      {
        id: 'erp-2',
        stepNumber: 2,
        code: 'ERP_02',
        title: 'Event Streaming & Distributed Ledgers',
        category: 'architecture',
        categoryLabel: 'Streaming & Ingestion',
        subtitle: 'Apache Kafka, Debezium CDC & Saga Orchestration',
        summary: 'Stream transaction events asynchronously across microservices with guaranteed exactly-once processing and compensation rollback sagas.',
        keyPractices: [
          'Change Data Capture (CDC) with Debezium pushing transactional logs to Kafka',
          'Distributed transaction handling using Saga orchestrators for complex multi-step workflows',
          'Dead Letter Queue (DLQ) automated replay mechanisms for transient consumer faults',
        ],
        deliverables: ['Kafka Schema Registry', 'Saga Orchestration Engine', 'CDC Pipeline'],
        techStack: ['Apache Kafka', 'Debezium', 'Go / .NET', 'gRPC'],
        kpis: [
          { label: 'Streaming Throughput', value: '85k evt/s' },
          { label: 'Message Loss', value: '0.000%' },
        ],
        icon: 'Server',
        phaseDuration: 'Phase 2 • Core Engine',
        bestPractices: ['Enforce idempotent consumers with deduplication windows.'],
      },
      {
        id: 'erp-3',
        stepNumber: 3,
        code: 'ERP_03',
        title: 'Enterprise Security & Audit Compliance',
        category: 'devops',
        categoryLabel: 'Security & Access',
        subtitle: 'OAuth2/OIDC, SAML 2.0 & Immutable Audit Trails',
        summary: 'Implement enterprise single sign-on (SSO), granular role-based access control (RBAC), and append-only audit logging.',
        keyPractices: [
          'SAML 2.0 & Okta / Azure AD enterprise identity federation',
          'Cryptographically verified append-only audit trail logging every state modification',
          'Zero-trust mTLS encryption across all internal microservice boundaries',
        ],
        deliverables: ['Identity Provider Config', 'Audit Log Schema', 'SOC2 Compliance Matrix'],
        techStack: ['Keycloak / Okta', 'OpenFGA', 'Vault', 'Cosign'],
        kpis: [
          { label: 'Auth Token Latency', value: '< 8ms' },
          { label: 'Audit Trail Coverage', value: '100%' },
        ],
        icon: 'ShieldCheck',
        phaseDuration: 'Phase 3 • Compliance',
        bestPractices: ['Store sensitive API keys and secrets in HashiCorp Vault with dynamic rotation.'],
      },
      {
        id: 'erp-4',
        stepNumber: 4,
        code: 'ERP_04',
        title: 'High-Availability Clustering & Disaster Recovery',
        category: 'devops',
        categoryLabel: 'Operations & SRE',
        subtitle: 'Patroni HA, Multi-Region Kubernetes & RTO/RPO SLAs',
        summary: 'Deploy self-healing database clusters and distributed application pods across multi-zone cloud regions with instant automated failover.',
        keyPractices: [
          'Patroni automated failover management for primary-replica PostgreSQL clusters',
          'Multi-region Kubernetes deployment with automated health check failover',
          'Continuous point-in-time recovery (PITR) backups with automated restore rehearsals',
        ],
        deliverables: ['Kubernetes Helm Charts', 'Disaster Recovery Runbook', 'HA Cluster Config'],
        techStack: ['Kubernetes', 'Patroni', 'Terraform', 'Prometheus'],
        kpis: [
          { label: 'System Availability', value: '99.99%' },
          { label: 'RPO (Recovery Point)', value: '< 1 sec' },
        ],
        icon: 'Activity',
        phaseDuration: 'Phase 4 • Live Operations',
        bestPractices: ['Schedule quarterly disaster recovery fire-drills to validate backup integrity.'],
      },
    ],
  },

  custom: {
    name: 'Custom Software & Distributed Systems Methodology',
    description: '4-step high-throughput engineering methodology for custom microservices, low-level algorithmic workloads, and high-concurrency architectures.',
    steps: [
      {
        id: 'cust-1',
        stepNumber: 1,
        code: 'CUST_01',
        title: 'Algorithmic Architecture & Memory Efficiency',
        category: 'architecture',
        categoryLabel: 'Core Foundations',
        subtitle: 'Go, Rust, Concurrency Primitives & Zero-Copy I/O',
        summary: 'Design high-throughput computational engines utilizing lock-free data structures, goroutines / async runtimes, and memory optimization.',
        keyPractices: [
          'Zero-copy buffer allocation and ring buffers for ultra-low latency memory pipelines',
          'Benchmarking CPU cache locality and lock contention profiling via pprof',
          'Domain-specific business logic isolation with pure functional primitives',
        ],
        deliverables: ['Core Algorithm Spec', 'Memory Benchmark Suite', 'Concurrency Graph'],
        techStack: ['Go', 'Rust', 'Python', 'C++ / JSI'],
        kpis: [
          { label: 'Memory Footprint', value: '< 45 MB' },
          { label: 'Execution Speed', value: 'Sub-millisecond' },
        ],
        icon: 'Zap',
        phaseDuration: 'Phase 1 • Core Engine',
        bestPractices: ['Profile memory allocations before and after every algorithm modification.'],
      },
      {
        id: 'cust-2',
        stepNumber: 2,
        code: 'CUST_02',
        title: 'Asynchronous Protocols & Binary Serialization',
        category: 'architecture',
        categoryLabel: 'Protocols & APIs',
        subtitle: 'gRPC Streaming, Protobuf & WebSocket Hubs',
        summary: 'Deliver real-time high-throughput communication using binary serialization and bidirectional multiplexed HTTP/2 streaming.',
        keyPractices: [
          'Protocol Buffers (Protobuf) schema definitions contract-locked in Git',
          'Bidirectional gRPC streaming with keep-alive heartbeats and backpressure management',
          'WebSocket edge clusters handling hundreds of thousands of concurrent connections',
        ],
        deliverables: ['Protobuf Schemas', 'gRPC Client Libraries', 'WebSocket Cluster Config'],
        techStack: ['gRPC', 'Protobuf', 'Envoy Gateway', 'Redis Pub/Sub'],
        kpis: [
          { label: 'Serialization Speed', value: '8x vs JSON' },
          { label: 'Concurrent Conns', value: '250k+' },
        ],
        icon: 'Server',
        phaseDuration: 'Phase 2 • Networking',
        bestPractices: ['Always apply backpressure handling on client streaming consumers.'],
      },
      {
        id: 'cust-3',
        stepNumber: 3,
        code: 'CUST_03',
        title: 'Load Stress Testing & Chaos Engineering',
        category: 'devops',
        categoryLabel: 'Resilience & QA',
        subtitle: 'k6 Distributed Load, Chaos Mesh & Fuzz Testing',
        summary: 'Validate extreme edge conditions, CPU thrashing, packet loss, and node failure scenarios before production release.',
        keyPractices: [
          'Distributed k6 load testing generating 100k+ virtual user traffic surges',
          'Chaos Mesh fault injection randomly dropping network packets and terminating pods',
          'Fuzz testing on input parsers to uncover edge-case memory panics',
        ],
        deliverables: ['k6 Load Scripts', 'Chaos Injection Scenarios', 'Stress Test Reports'],
        techStack: ['k6', 'Chaos Mesh', 'Grafana k6 Cloud', 'SonarQube'],
        kpis: [
          { label: 'Surge Capacity', value: '10x Peak' },
          { label: 'Fault Recovery Time', value: '< 2.5s' },
        ],
        icon: 'ShieldCheck',
        phaseDuration: 'Phase 3 • Verification',
        bestPractices: ['Run chaos experiments continuously in staging rather than just once before launch.'],
      },
      {
        id: 'cust-4',
        stepNumber: 4,
        code: 'CUST_04',
        title: 'Bare-Metal / Cloud GitOps Orchestration',
        category: 'devops',
        categoryLabel: 'Deployment & SRE',
        subtitle: 'Kubernetes Operator, eBPF Tracing & ArgoCD',
        summary: 'Automate deployment topologies with declarative Kubernetes custom resources, eBPF kernel network observability, and canary deployments.',
        keyPractices: [
          'Kubernetes Custom Resource Definitions (CRDs) managing custom application state',
          'eBPF kernel-level tracing via Cilium for real-time network visibility',
          'ArgoCD GitOps synchronization with automated canary rollback guardrails',
        ],
        deliverables: ['Custom Operator Controller', 'Helm Charts', 'eBPF Tracing Dashboard'],
        techStack: ['Kubernetes', 'ArgoCD', 'Cilium / eBPF', 'Prometheus'],
        kpis: [
          { label: 'Deployment Lead Time', value: '< 15 mins' },
          { label: 'Uptime SLA', value: '99.99%' },
        ],
        icon: 'GitBranch',
        phaseDuration: 'Phase 4 • Operations',
        bestPractices: ['Utilize eBPF for network observability with zero userspace overhead.'],
      },
    ],
  },
};
