import { WebTechPlanet } from '@/types/animation';

export const allTechPlanets: WebTechPlanet[] = [
  {
    id: 'react',
    name: 'React',
    domain: 'web',
    category: 'frontend',
    orbitRadius: 150,
    speed: 0.7,
    initialAngle: 0,
    size: 42,
    color: '#00d8ff',
    glowColor: 'rgba(0, 216, 255, 0.4)',
    iconName: 'Atom',
    role: 'UI Component Architecture',
    description: 'Declarative component-based library for crafting interactive, highly responsive web user interfaces.',
    keyFeatures: ['Virtual DOM & Reconciliation', 'React Server Components', 'Hooks & Concurrent Mode'],
    techStackTier: 'Core Frontend',
    popularity: '98% Industry Adoption',
    benchmarks: 'Sub-16ms frame render time'
  },
  {
    id: 'typescript',
    name: 'TypeScript',
    domain: 'web',
    category: 'frontend',
    orbitRadius: 150,
    speed: 0.7,
    initialAngle: (Math.PI * 2) / 3,
    size: 38,
    color: '#3178c6',
    glowColor: 'rgba(49, 120, 198, 0.4)',
    iconName: 'FileCode2',
    role: 'Type Safety & Ergonomics',
    description: 'Strict syntactic superset of JavaScript adding static type validation, autocomplete, and robust refactoring.',
    keyFeatures: ['Compile-time Type Checking', 'Generics & Utility Types', 'Superior IDE Intelligence'],
    techStackTier: 'Core Language',
    popularity: '95% Enterprise Choice',
    benchmarks: 'Zero runtime bundle overhead'
  },
  {
    id: 'tailwind',
    name: 'Tailwind CSS',
    domain: 'web',
    category: 'frontend',
    orbitRadius: 150,
    speed: 0.7,
    initialAngle: (Math.PI * 4) / 3,
    size: 36,
    color: '#38bdf8',
    glowColor: 'rgba(56, 189, 248, 0.4)',
    iconName: 'Sparkles',
    role: 'Design System & Styling',
    description: 'Utility-first CSS framework enabling rapid, highly consistent, and maintainable responsive interface design.',
    keyFeatures: ['Zero Runtime Overhead', 'JIT Engine Compilation', 'Design Token System'],
    techStackTier: 'Styling Layer',
    popularity: '92% Modern Web Standard',
    benchmarks: '<15KB production stylesheet'
  },
  {
    id: 'nextjs',
    name: 'Next.js',
    domain: 'web',
    category: 'frontend',
    orbitRadius: 240,
    speed: 0.48,
    initialAngle: 0.5,
    size: 40,
    color: '#ffffff',
    glowColor: 'rgba(255, 255, 255, 0.4)',
    iconName: 'Layers',
    role: 'Full-Stack Web Framework',
    description: 'Production React framework offering hybrid Static Site Generation (SSG), Server-Side Rendering (SSR), and Edge Routing.',
    keyFeatures: ['App Router & RSC', 'Automatic Image/Font Optimization', 'Edge API Handlers'],
    techStackTier: 'Meta-Framework',
    popularity: '94% Production Grade',
    benchmarks: '99+ Google Lighthouse score'
  },
  {
    id: 'nodejs',
    name: 'Node.js',
    domain: 'web',
    category: 'backend',
    orbitRadius: 240,
    speed: 0.48,
    initialAngle: 0.5 + (Math.PI * 2) / 3,
    size: 40,
    color: '#68a063',
    glowColor: 'rgba(104, 160, 99, 0.4)',
    iconName: 'Server',
    role: 'V8 Server Execution Engine',
    description: 'Asynchronous event-driven JavaScript runtime built on Chrome V8 engine for building scalable network servers.',
    keyFeatures: ['Non-blocking Event Loop', 'NPM Ecosystem Hub', 'High Throughput I/O'],
    techStackTier: 'Backend Runtime',
    popularity: '97% Backend Standard',
    benchmarks: '100k+ concurrent connections'
  },
  {
    id: 'graphql',
    name: 'GraphQL & REST',
    domain: 'web',
    category: 'backend',
    orbitRadius: 240,
    speed: 0.48,
    initialAngle: 0.5 + (Math.PI * 4) / 3,
    size: 36,
    color: '#e535ab',
    glowColor: 'rgba(229, 53, 171, 0.4)',
    iconName: 'Zap',
    role: 'API Contract & Schema',
    description: 'Declarative query language and architectural patterns for precise client-driven data fetching without over-fetching.',
    keyFeatures: ['Strict Schema Contracts', 'Single-Roundtrip Queries', 'Real-time Subscriptions'],
    techStackTier: 'API Layer',
    popularity: '88% Scalable Architecture',
    benchmarks: 'Zero over-fetching payload'
  },
  {
    id: 'postgres',
    name: 'PostgreSQL',
    domain: 'web',
    category: 'database',
    orbitRadius: 330,
    speed: 0.32,
    initialAngle: 1.2,
    size: 40,
    color: '#336791',
    glowColor: 'rgba(51, 103, 145, 0.5)',
    iconName: 'Database',
    role: 'ACID Relational Database',
    description: 'Advanced open-source relational database system with proven transactional reliability, JSONB indexing, and concurrency.',
    keyFeatures: ['ACID Compliance', 'JSONB & Vector Extensions', 'Complex Query Optimization'],
    techStackTier: 'Persistent Data',
    popularity: '96% Enterprise DB',
    benchmarks: '99.999% data consistency'
  },
  {
    id: 'redis',
    name: 'Redis',
    domain: 'web',
    category: 'database',
    orbitRadius: 330,
    speed: 0.32,
    initialAngle: 1.2 + (Math.PI * 2) / 3,
    size: 34,
    color: '#dc382d',
    glowColor: 'rgba(220, 56, 45, 0.45)',
    iconName: 'Zap',
    role: 'In-Memory Cache & Pub/Sub',
    description: 'Ultra-low latency in-memory data store used for microsecond caching, distributed sessions, and message brokering.',
    keyFeatures: ['Sub-millisecond Latency', 'Pub/Sub Messaging', 'TTL Key Expiration'],
    techStackTier: 'In-Memory Cache',
    popularity: '91% High-Scale Systems',
    benchmarks: '<1ms response time'
  },
  {
    id: 'docker',
    name: 'Docker & K8s',
    domain: 'web',
    category: 'devops',
    orbitRadius: 420,
    speed: 0.22,
    initialAngle: 0.8,
    size: 38,
    color: '#2496ed',
    glowColor: 'rgba(36, 150, 237, 0.4)',
    iconName: 'Box',
    role: 'Containerization & Cloud',
    description: 'Standardized container packaging and cluster orchestration for repeatable, isolated deployments anywhere.',
    keyFeatures: ['Reproducible Build Environments', 'Automated Scaling & Self-healing', 'Zero-Downtime Releases'],
    techStackTier: 'Cloud Infrastructure',
    popularity: '95% Cloud Native Standard',
    benchmarks: 'Zero-downtime rolling updates'
  },
  {
    id: 'wasm',
    name: 'WebAssembly',
    domain: 'web',
    category: 'frontend',
    orbitRadius: 420,
    speed: 0.22,
    initialAngle: 0.8 + (Math.PI * 2) / 3,
    size: 34,
    color: '#654ff0',
    glowColor: 'rgba(101, 79, 240, 0.4)',
    iconName: 'Cpu',
    role: 'High-Performance Binary',
    description: 'Binary instruction format for near-native performance execution of C++, Rust, and Go code in the modern web browser.',
    keyFeatures: ['Near-Native 60FPS Execution', 'Memory Safety Sandbox', 'Audio/Video/3D Processing'],
    techStackTier: 'High-Performance',
    popularity: '84% Advanced Web',
    benchmarks: '1.2x of native C++ speed'
  },

  {
    id: 'react-native',
    name: 'React Native',
    domain: 'mobile',
    category: 'mobile-ui',
    orbitRadius: 150,
    speed: 0.72,
    initialAngle: 0.2,
    size: 42,
    color: '#61dafb',
    glowColor: 'rgba(97, 218, 251, 0.45)',
    iconName: 'Smartphone',
    role: 'Cross-Platform Native UI',
    description: 'Write once, run natively across iOS and Android with direct bridge-less JSI fabric bindings and native widget rendering.',
    keyFeatures: ['New Architecture (Fabric & TurboModules)', 'OTA Live Code Updates', 'Single Codebase 95% Code Sharing'],
    techStackTier: 'Mobile Framework',
    popularity: '93% App Store Dominance',
    benchmarks: '60-120 FPS native UI thread'
  },
  {
    id: 'flutter',
    name: 'Flutter & Dart',
    domain: 'mobile',
    category: 'mobile-ui',
    orbitRadius: 150,
    speed: 0.72,
    initialAngle: 0.2 + (Math.PI * 2) / 3,
    size: 40,
    color: '#02569b',
    glowColor: 'rgba(2, 86, 155, 0.45)',
    iconName: 'Cpu',
    role: 'Impeller High-Speed Canvas',
    description: 'Google multi-platform UI toolkit compiled directly to ARM machine code using the hardware-accelerated Impeller engine.',
    keyFeatures: ['Impeller Vulkan/Metal Rendering', 'Stateful Hot Reload', 'Pixel-Perfect Custom UI Widgets'],
    techStackTier: 'Cross-Platform Engine',
    popularity: '90% High Performance',
    benchmarks: 'Zero shader compilation jank'
  },
  {
    id: 'swift-ios',
    name: 'Swift & SwiftUI',
    domain: 'mobile',
    category: 'native',
    orbitRadius: 150,
    speed: 0.72,
    initialAngle: 0.2 + (Math.PI * 4) / 3,
    size: 38,
    color: '#f05138',
    glowColor: 'rgba(240, 81, 56, 0.45)',
    iconName: 'Layers',
    role: 'iOS Native Flagship',
    description: 'Apple modern language and declarative UI paradigm with direct access to Metal, CoreML, Dynamic Island, and Live Activities.',
    keyFeatures: ['Declarative SwiftUI State', 'Metal GPU Acceleration', 'Apple Watch / VisionOS Parity'],
    techStackTier: 'Apple Native',
    popularity: '96% iOS Standard',
    benchmarks: 'Direct hardware register speed'
  },
  {
    id: 'kotlin-android',
    name: 'Kotlin & Compose',
    domain: 'mobile',
    category: 'native',
    orbitRadius: 240,
    speed: 0.46,
    initialAngle: 1.0,
    size: 40,
    color: '#7f52ff',
    glowColor: 'rgba(127, 82, 255, 0.45)',
    iconName: 'Sparkles',
    role: 'Modern Android Core',
    description: 'Jetpack Compose reactive declarative framework powered by Kotlin coroutines, flows, and Android hardware acceleration.',
    keyFeatures: ['Jetpack Compose Declarative UI', 'Coroutines & Asynchronous Flow', 'Multiplatform (KMP) Shared Logic'],
    techStackTier: 'Android Native',
    popularity: '95% Android Standard',
    benchmarks: 'Optimized bytecode runtime'
  },
  {
    id: 'expo',
    name: 'Expo Ecosystem',
    domain: 'mobile',
    category: 'tooling',
    orbitRadius: 240,
    speed: 0.46,
    initialAngle: 1.0 + (Math.PI * 2) / 3,
    size: 36,
    color: '#000020',
    glowColor: 'rgba(255, 255, 255, 0.4)',
    iconName: 'Box',
    role: 'Universal Mobile Toolchain',
    description: 'Complete suite of tools, libraries, and cloud builds (EAS) powering modern React Native development and app store deployment.',
    keyFeatures: ['EAS Cloud Build & Submit', 'File-based Expo Router', 'Universal Push & Deep Linking'],
    techStackTier: 'Mobile Toolchain',
    popularity: '91% Developer Velocity',
    benchmarks: 'Instant Over-The-Air Patches'
  },
  {
    id: 'realm-sqlite',
    name: 'Realm & SQLite',
    domain: 'mobile',
    category: 'database',
    orbitRadius: 240,
    speed: 0.46,
    initialAngle: 1.0 + (Math.PI * 4) / 3,
    size: 36,
    color: '#394497',
    glowColor: 'rgba(57, 68, 151, 0.45)',
    iconName: 'Database',
    role: 'Offline-First Local DB',
    description: 'Embedded object database and relational storage with zero-copy queries, background sync, and instant offline-first capabilities.',
    keyFeatures: ['Zero-Copy Query Engine', 'Offline-First Auto Sync', 'AES-256 Storage Encryption'],
    techStackTier: 'Mobile Storage',
    popularity: '89% Offline-First Apps',
    benchmarks: '<5ms localized complex query'
  },
  {
    id: 'fastlane',
    name: 'Fastlane & CI/CD',
    domain: 'mobile',
    category: 'devops',
    orbitRadius: 330,
    speed: 0.3,
    initialAngle: 1.8,
    size: 36,
    color: '#00f2fe',
    glowColor: 'rgba(0, 242, 254, 0.45)',
    iconName: 'Zap',
    role: 'App Store Automation',
    description: 'Automates building, code signing, screenshot generation, and seamless deployment to TestFlight and Google Play.',
    keyFeatures: ['Match Code Signing Sync', 'Automated App Store Metadata', 'TestFlight & Play Beta Distro'],
    techStackTier: 'Mobile Pipeline',
    popularity: '94% Mobile DevOps',
    benchmarks: 'One-command store submission'
  },
  {
    id: 'firebase-fcm',
    name: 'FCM & Telemetry',
    domain: 'mobile',
    category: 'integration',
    orbitRadius: 330,
    speed: 0.3,
    initialAngle: 1.8 + (Math.PI * 2) / 3,
    size: 34,
    color: '#ffa000',
    glowColor: 'rgba(255, 160, 0, 0.45)',
    iconName: 'Radio',
    role: 'Push & Device Services',
    description: 'Cross-platform push messaging, crashlytics real-time telemetry, remote configuration, and device token management.',
    keyFeatures: ['APNs & FCM Unified Pipeline', 'Crashlytics Real-time Stack Traces', 'Device Geofencing & Sensors'],
    techStackTier: 'Device Services',
    popularity: '96% Mobile Notifications',
    benchmarks: '<250ms worldwide push delivery'
  },

  {
    id: 'sap-hana',
    name: 'SAP S/4HANA',
    domain: 'erp',
    category: 'core-erp',
    orbitRadius: 150,
    speed: 0.65,
    initialAngle: 0.4,
    size: 44,
    color: '#008fd3',
    glowColor: 'rgba(0, 143, 211, 0.45)',
    iconName: 'Server',
    role: 'Enterprise Core Ledger & ERP',
    description: 'In-memory enterprise resource planning suite delivering real-time transactions, supply chain intelligence, and financial ledgers.',
    keyFeatures: ['In-Memory Columnar HANA DB', 'Fiori UI / BTP Integration', 'Global Multicurrency Ledger'],
    techStackTier: 'Tier-1 ERP Core',
    popularity: '92% Global Fortune 500',
    benchmarks: 'Billion-record real-time analytics'
  },
  {
    id: 'odoo-erp',
    name: 'Odoo Enterprise',
    domain: 'erp',
    category: 'core-erp',
    orbitRadius: 150,
    speed: 0.65,
    initialAngle: 0.4 + (Math.PI * 2) / 3,
    size: 38,
    color: '#714b67',
    glowColor: 'rgba(113, 75, 103, 0.45)',
    iconName: 'Box',
    role: 'Modular Business Engine',
    description: 'Highly extensible modular ERP covering CRM, Manufacturing (MRP), Inventory, Accounting, and Human Capital Management.',
    keyFeatures: ['Python/PostgreSQL Modular ORM', 'Automated Double-Entry Ledger', 'Multi-Warehouse Inventory Tracking'],
    techStackTier: 'Mid-Market & Agile ERP',
    popularity: '89% High Flexibility',
    benchmarks: 'Rapid modular onboarding'
  },
  {
    id: 'dynamics-365',
    name: 'MS Dynamics 365',
    domain: 'erp',
    category: 'core-erp',
    orbitRadius: 150,
    speed: 0.65,
    initialAngle: 0.4 + (Math.PI * 4) / 3,
    size: 38,
    color: '#0078d4',
    glowColor: 'rgba(0, 120, 212, 0.45)',
    iconName: 'Layers',
    role: 'Enterprise Operations & CRM',
    description: 'Microsoft cloud ERP and CRM platform integrating Power Platform workflows, Azure Dataverse, and Copilot intelligence.',
    keyFeatures: ['Azure Dataverse Backbone', 'Power Automate Workflow Hub', 'Supply Chain Insights'],
    techStackTier: 'Cloud ERP Suite',
    popularity: '91% Enterprise Ecosystem',
    benchmarks: 'Native Office 365 / Azure sync'
  },
  {
    id: 'apache-kafka',
    name: 'Apache Kafka',
    domain: 'erp',
    category: 'integration',
    orbitRadius: 240,
    speed: 0.44,
    initialAngle: 1.4,
    size: 40,
    color: '#e0234e',
    glowColor: 'rgba(224, 35, 78, 0.45)',
    iconName: 'Zap',
    role: 'Distributed Event Streaming',
    description: 'Fault-tolerant distributed event stream backbone decoupling enterprise transactions, inventory sync, and audit trails.',
    keyFeatures: ['Event Sourcing Architecture', 'Exactly-Once Processing Semantics', 'Multi-Terabyte Daily Throughput'],
    techStackTier: 'Enterprise Event Bus',
    popularity: '96% Event-Driven ERP',
    benchmarks: 'Millions of events/sec at <2ms'
  },
  {
    id: 'temporal-workflow',
    name: 'Temporal & Camunda',
    domain: 'erp',
    category: 'integration',
    orbitRadius: 240,
    speed: 0.44,
    initialAngle: 1.4 + (Math.PI * 2) / 3,
    size: 36,
    color: '#29c78f',
    glowColor: 'rgba(41, 199, 143, 0.45)',
    iconName: 'GitBranch',
    role: 'Durable Saga Orchestrator',
    description: 'Resilient workflow engine guaranteeing stateful transaction execution, compensating rollbacks, and distributed approvals.',
    keyFeatures: ['Durable Execution Sagas', 'Automated Failure Compensation', 'BPMN 2.0 Process Governance'],
    techStackTier: 'Workflow Orchestration',
    popularity: '88% Mission-Critical Sagas',
    benchmarks: 'Zero lost state on server crashes'
  },
  {
    id: 'enterprise-dwh',
    name: 'ClickHouse & Snowflake',
    domain: 'erp',
    category: 'database',
    orbitRadius: 330,
    speed: 0.28,
    initialAngle: 0.9,
    size: 38,
    color: '#f59e0b',
    glowColor: 'rgba(245, 158, 11, 0.45)',
    iconName: 'Database',
    role: 'Columnar OLAP Data Lake',
    description: 'High-speed analytical database enabling instantaneous financial forecasting, executive dashboards, and supply chain telemetry.',
    keyFeatures: ['Columnar Data Compression', 'Sub-second Aggregation over Billions', 'Near-Instant Ad-hoc SQL'],
    techStackTier: 'Enterprise Analytics',
    popularity: '93% Big Data & BI',
    benchmarks: '100M rows scanned in <50ms'
  },
  {
    id: 'keycloak-iam',
    name: 'Keycloak & SAML IAM',
    domain: 'erp',
    category: 'security',
    orbitRadius: 330,
    speed: 0.28,
    initialAngle: 0.9 + (Math.PI * 2) / 3,
    size: 36,
    color: '#10b981',
    glowColor: 'rgba(16, 185, 129, 0.45)',
    iconName: 'Shield',
    role: 'Enterprise SSO & RBAC',
    description: 'Identity access management securing enterprise access via OpenID Connect, SAML 2.0, Fine-Grained RBAC, and Immutable Audit Logs.',
    keyFeatures: ['Enterprise SAML 2.0 / OIDC', 'Role & Permission Hierarchy', 'Tamper-Proof Audit Trails'],
    techStackTier: 'Security & Governance',
    popularity: '95% Compliance Standard',
    benchmarks: 'SOC2 / HIPAA / GDPR ready'
  },
  {
    id: 'mulesoft-gateway',
    name: 'MuleSoft & Kong',
    domain: 'erp',
    category: 'integration',
    orbitRadius: 420,
    speed: 0.2,
    initialAngle: 2.1,
    size: 36,
    color: '#00a1e0',
    glowColor: 'rgba(0, 161, 224, 0.45)',
    iconName: 'Globe',
    role: 'Enterprise API Gateway',
    description: 'High-throughput enterprise gateway mediating EDI, legacy SOAP services, REST microservices, and partner integrations.',
    keyFeatures: ['EDI / B2B Protocol Translation', 'Rate-limiting & Token Validation', 'Universal Enterprise Connector Hub'],
    techStackTier: 'Integration Gateway',
    popularity: '90% Legacy Bridge',
    benchmarks: 'Sub-millisecond proxy routing'
  },

  {
    id: 'golang',
    name: 'Go (Golang)',
    domain: 'custom',
    category: 'systems',
    orbitRadius: 150,
    speed: 0.68,
    initialAngle: 0.1,
    size: 42,
    color: '#00add8',
    glowColor: 'rgba(0, 173, 216, 0.45)',
    iconName: 'Cpu',
    role: 'High-Concurrency Systems Core',
    description: 'Fast, statically typed compiled language featuring lightweight goroutines and channels for hyper-scalable cloud backend systems.',
    keyFeatures: ['Lightweight CSP Goroutines', 'Garbage Collected Sub-ms Pauses', 'Static Native Binary Compilation'],
    techStackTier: 'Microservices & Infrastructure',
    popularity: '96% High-Throughput Systems',
    benchmarks: '1M+ concurrent goroutines'
  },
  {
    id: 'rust',
    name: 'Rust Systems',
    domain: 'custom',
    category: 'low-level',
    orbitRadius: 150,
    speed: 0.68,
    initialAngle: 0.1 + (Math.PI * 2) / 3,
    size: 42,
    color: '#dea584',
    glowColor: 'rgba(222, 165, 132, 0.45)',
    iconName: 'Shield',
    role: 'Zero-Cost Memory Safety',
    description: 'Blazing fast systems language providing mathematically proven memory safety without a garbage collector for mission-critical logic.',
    keyFeatures: ['Compile-Time Borrow Checker', 'Zero-Cost Abstractions', 'Deterministic Memory & CPU Utilization'],
    techStackTier: 'Mission-Critical Core',
    popularity: '95% Developer Favorite',
    benchmarks: 'Sub-microsecond execution latency'
  },
  {
    id: 'python-ai',
    name: 'Python & PyTorch',
    domain: 'custom',
    category: 'ai-data',
    orbitRadius: 150,
    speed: 0.68,
    initialAngle: 0.1 + (Math.PI * 4) / 3,
    size: 40,
    color: '#3776ab',
    glowColor: 'rgba(55, 118, 171, 0.45)',
    iconName: 'Sparkles',
    role: 'Algorithmic & AI Pipelines',
    description: 'Dominant language for mathematical modeling, custom algorithmic automation, deep learning neural networks, and automated inference.',
    keyFeatures: ['PyTorch & CUDA Acceleration', 'FastAPI High-Speed Ingestion', 'Mathematical Vector Operations'],
    techStackTier: 'AI & Data Science',
    popularity: '99% ML & AI Standard',
    benchmarks: 'GPU-accelerated tensor computation'
  },
  {
    id: 'cpp-systems',
    name: 'C++ & Low Latency',
    domain: 'custom',
    category: 'low-level',
    orbitRadius: 240,
    speed: 0.45,
    initialAngle: 1.1,
    size: 38,
    color: '#00599c',
    glowColor: 'rgba(0, 89, 156, 0.45)',
    iconName: 'Cpu',
    role: 'Bare-Metal Performance',
    description: 'Hardware-level control and manual memory management for financial trading engines, embedded microcontrollers, and real-time processing.',
    keyFeatures: ['Direct Cache-Line Alignment', 'SIMD Parallel Processing', 'Deterministic Real-Time Scheduling'],
    techStackTier: 'Ultra-Low Latency',
    popularity: '90% High Frequency Core',
    benchmarks: 'Nanosecond instruction cycles'
  },
  {
    id: 'nats-rabbitmq',
    name: 'NATS & RabbitMQ',
    domain: 'custom',
    category: 'distributed',
    orbitRadius: 240,
    speed: 0.45,
    initialAngle: 1.1 + (Math.PI * 2) / 3,
    size: 38,
    color: '#ff6600',
    glowColor: 'rgba(255, 102, 0, 0.45)',
    iconName: 'Zap',
    role: 'Distributed Messaging Fabric',
    description: 'Lightweight, ultra-fast distributed messaging systems providing publish-subscribe, request-reply, and streaming message queues.',
    keyFeatures: ['Sub-millisecond Message Routing', 'Clustered Multi-Region Mesh', 'AMQP & JetStream Persistence'],
    techStackTier: 'Message Broker',
    popularity: '92% Distributed Systems',
    benchmarks: '10M+ messages/sec routing speed'
  },
  {
    id: 'grpc-protobuf',
    name: 'gRPC & Protobuf',
    domain: 'custom',
    category: 'distributed',
    orbitRadius: 240,
    speed: 0.45,
    initialAngle: 1.1 + (Math.PI * 4) / 3,
    size: 36,
    color: '#244c5a',
    glowColor: 'rgba(36, 76, 90, 0.45)',
    iconName: 'Layers',
    role: 'Binary RPC Transport',
    description: 'High-performance binary serialization protocol and HTTP/2 transport for inter-service communication with minimal overhead.',
    keyFeatures: ['Strict Protobuf Schema Contracts', 'Bi-Directional Streaming', '10x Faster than JSON over HTTP/1'],
    techStackTier: 'Inter-Service Protocol',
    popularity: '94% Cloud Microservices',
    benchmarks: '10x throughput vs JSON REST'
  },
  {
    id: 'timescaledb-iot',
    name: 'Timescale & IoT',
    domain: 'custom',
    category: 'database',
    orbitRadius: 330,
    speed: 0.3,
    initialAngle: 0.6,
    size: 38,
    color: '#fdb515',
    glowColor: 'rgba(253, 181, 21, 0.45)',
    iconName: 'Database',
    role: 'Time-Series Telemetry Engine',
    description: 'Purpose-built time-series relational engine ingesting real-time IoT sensor telemetry, server metrics, and financial ticks.',
    keyFeatures: ['Hypertables Automatic Partitioning', '90%+ Data Compression Ratios', 'Continuous Real-Time Aggregates'],
    techStackTier: 'Time-Series Storage',
    popularity: '89% IoT & Metrics Systems',
    benchmarks: 'Millions of metrics ingested/sec'
  },
  {
    id: 'ebpf-observability',
    name: 'eBPF & Kernel Telemetry',
    domain: 'custom',
    category: 'low-level',
    orbitRadius: 330,
    speed: 0.3,
    initialAngle: 0.6 + (Math.PI * 2) / 3,
    size: 36,
    color: '#ff3e00',
    glowColor: 'rgba(255, 62, 0, 0.45)',
    iconName: 'Shield',
    role: 'Kernel-Level Programmability',
    description: 'Runs sandboxed programs inside the Linux kernel without modifying kernel code, providing zero-overhead observability and firewall security.',
    keyFeatures: ['Kernel-Space Packet Filtering', 'Zero-Overhead Profiling', 'Real-Time Threat Prevention'],
    techStackTier: 'Kernel Observability',
    popularity: '91% Modern Linux Cloud',
    benchmarks: 'Zero-overhead kernel probes'
  }
];

export const domainMeta = {
  web: {
    title: 'Modern Web Engineering',
    badge: 'Web 3.0 & Cloud',
    coreLabel: 'WEB',
    coreSub: 'ECOSYSTEM',
    accentColor: '#00d8ff',
    description: 'Full-stack reactive web applications, edge rendering architectures, distributed caching, and micro-frontends.'
  },
  mobile: {
    title: 'Native & Cross-Platform Mobile',
    badge: 'iOS · Android · Cross-Platform',
    coreLabel: 'MOBILE',
    coreSub: 'DEVICE CORE',
    accentColor: '#61dafb',
    description: 'High-framerate iOS & Android applications with offline-first local databases, push notifications, and automated App Store delivery.'
  },
  erp: {
    title: 'Enterprise Resource Planning & Sagas',
    badge: 'SAP · Odoo · Dynamics · Kafka',
    coreLabel: 'ERP',
    coreSub: 'ENTERPRISE CORE',
    accentColor: '#008fd3',
    description: 'Mission-critical enterprise software, transactional double-entry ledgers, event-driven integrations, and durable workflow sagas.'
  },
  custom: {
    title: 'Custom Systems & High-Throughput Engineering',
    badge: 'Go · Rust · Python · Distributed Systems',
    coreLabel: 'CUSTOM',
    coreSub: 'SYSTEMS CORE',
    accentColor: '#10b981',
    description: 'Bespoke high-performance software engineering, low-latency microservices, algorithmic pipelines, and distributed messaging architectures.'
  }
};
