import { ServiceItem } from '@/types/services'

export const SERVICES: ServiceItem[] = [
  {
    id: 'web-development',
    slug: 'web-development',
    title: 'Web Development',
    eyebrow: 'Frontend & Web Platforms',
    description: 'We build responsive web applications, customer portals, dashboards, internal tools, SaaS products, and other browser-based systems.',
    longDescription: 'We build responsive web applications, customer portals, dashboards, internal tools, SaaS products, and other browser-based systems designed for speed, security, and seamless user experiences.',
    iconName: 'Layout',
    features: [
      'Responsive Web Applications',
      'Customer Portals & Dashboards',
      'Internal Workflow Tools',
      'SaaS Platforms & Web Systems',
    ],
    technologies: ['React', 'Next.js', 'TypeScript', 'Tailwind CSS', 'Node.js'],
    benefits: [
      { title: 'Sub-Second First Paint', description: 'Optimized server-side rendering and edge caching delivering top performance scores.' },
      { title: 'Modern User Experience', description: 'Intuitive interface patterns that simplify complex workflows for end users.' },
      { title: 'Scalable Architecture', description: 'Modular component architecture built to expand smoothly as your product grows.' },
    ],
  },
  {
    id: 'mobile-development',
    slug: 'mobile-development',
    title: 'Mobile Development',
    eyebrow: 'iOS & Android Applications',
    description: 'We build mobile applications for iOS and Android, including cross-platform applications when one shared codebase makes sense.',
    longDescription: 'We build mobile applications for iOS and Android, including cross-platform applications when one shared codebase makes sense, pairing native device capabilities with fluid interfaces.',
    iconName: 'Smartphone',
    features: [
      'iOS & Android Applications',
      'Cross-Platform Apps (Flutter / React Native)',
      'Native Swift & Kotlin Modules',
      'Offline-First Local Storage & Sync',
    ],
    technologies: ['Flutter', 'React Native', 'Swift', 'Kotlin', 'Firebase'],
    benefits: [
      { title: 'Smooth 60FPS UI', description: 'Responsive animations and instant touch response across low-end and flagship devices.' },
      { title: 'Offline Reliability', description: 'Local caching and background sync ensuring continuous operation during network drops.' },
      { title: 'Efficient Delivery', description: 'Shared codebase architecture enabling simultaneous iOS and Android releases.' },
    ],
  },
  {
    id: 'backend-api-development',
    slug: 'backend-api-development',
    title: 'Backend & API Development',
    eyebrow: 'Services & Integrations',
    description: 'We build APIs, microservices, integrations, authentication systems, business logic, and the backend services that power applications.',
    longDescription: 'We build APIs, microservices, integrations, authentication systems, business logic, and the backend services that power applications with high throughput and low latency.',
    iconName: 'Server',
    features: [
      'REST & gRPC Microservices',
      'Third-Party Integrations & Webhooks',
      'OAuth2 & Authentication Systems',
      'High-Throughput Data Pipelines',
    ],
    technologies: ['Node.js', 'Go', 'Python', 'PostgreSQL', 'Redis', 'Kafka'],
    benefits: [
      { title: 'Low-Latency Queries', description: 'Optimized database schema design and connection pooling for rapid response times.' },
      { title: 'Resilient Integrations', description: 'Automated retry and circuit-breaker mechanisms preventing third-party cascade failures.' },
      { title: 'Robust Security', description: 'Enterprise authentication, encryption, and granular rate-limiting built in from day one.' },
    ],
  },
  {
    id: 'enterprise-software',
    slug: 'enterprise-software',
    title: 'Enterprise Software',
    eyebrow: 'Mission-Critical Systems',
    description: 'We build and improve business-critical systems, internal applications, workflow tools, financial platforms, and system integrations.',
    longDescription: 'We build and improve business-critical systems, internal applications, workflow tools, financial platforms, and system integrations tailored precisely to complex operational logic.',
    iconName: 'Workflow',
    features: [
      'Custom ERP & Resource Architectures',
      'Financial & Transactional Ledgers',
      'Business Workflow Automation',
      'Multi-Tenant Enterprise Portals',
    ],
    technologies: ['PostgreSQL', '.NET', 'Go', 'React', 'Docker', 'Kubernetes'],
    benefits: [
      { title: 'Unified Data Operations', description: 'Single consolidated view across operations, inventory, and financial reporting.' },
      { title: 'Strict Data Integrity', description: 'ACID transactional schemas and comprehensive audit logs protecting critical records.' },
      { title: 'Zero Licensing Lock-In', description: 'Full source code and intellectual property ownership delivered to your organization.' },
    ],
  },
  {
    id: 'cloud-devops',
    slug: 'cloud-devops',
    title: 'Cloud & DevOps',
    eyebrow: 'Infrastructure & Automation',
    description: 'We help applications run reliably through cloud infrastructure, containers, CI/CD pipelines, deployment automation, monitoring, and scaling.',
    longDescription: 'We help applications run reliably through cloud infrastructure, containers, CI/CD pipelines, deployment automation, monitoring, and scaling for maximum uptime.',
    iconName: 'Cloud',
    features: [
      'Infrastructure as Code (Terraform)',
      'Kubernetes & Container Orchestration',
      'Automated CI/CD Release Pipelines',
      'Monitoring, Alerting & SRE Dashboards',
    ],
    technologies: ['AWS', 'GCP', 'Docker', 'Kubernetes', 'Terraform', 'Prometheus'],
    benefits: [
      { title: 'Zero-Downtime Releases', description: 'Automated blue/green and canary deployment pipelines with instant rollback triggers.' },
      { title: 'High Availability', description: 'Multi-zone redundancy and auto-scaling accommodating unexpected traffic surges.' },
      { title: 'Cost Optimization', description: 'Efficient cloud resource provisioning reducing unnecessary infrastructure overhead.' },
    ],
  },
  {
    id: 'ai-automation',
    slug: 'ai-automation',
    title: 'AI & Automation',
    eyebrow: 'Intelligent Workflows',
    description: 'We use AI and automation where they solve a real problem, including intelligent assistants, workflow automation, data processing, and AI integrations.',
    longDescription: 'We use AI and automation where they solve a real problem, including intelligent assistants, workflow automation, data processing, and AI integrations that eliminate manual bottlenecks.',
    iconName: 'Sparkles',
    features: [
      'Intelligent Assistants & Chatbots',
      'Automated Document Processing (OCR)',
      'Workflow & RPA Automation',
      'Custom LLM & API Integrations',
    ],
    technologies: ['Python', 'LangChain', 'OpenAI', 'FastAPI', 'PostgreSQL'],
    benefits: [
      { title: 'Automated Data Extraction', description: 'High-accuracy parsing of invoices, receipts, and unstructured documents.' },
      { title: 'Operational Efficiency', description: 'Eliminating hundreds of hours of repetitive manual data entry tasks.' },
      { title: 'Practical Integration', description: 'Targeted AI models solving concrete business problems with measurable ROI.' },
    ],
  },
  {
    id: 'software-modernization',
    slug: 'software-modernization',
    title: 'Software Modernization',
    eyebrow: 'Architecture & Migration',
    description: 'We help modernize older applications by improving architecture, moving workloads to the cloud, introducing APIs or microservices, and replacing outdated technology.',
    longDescription: 'We help modernize older applications by improving architecture, moving workloads to the cloud, introducing APIs or microservices, and replacing outdated technology safely without disrupting operations.',
    iconName: 'GitMerge',
    features: [
      'Monolith to Microservices Transition',
      'Cloud Migration & Containerization',
      'Database Optimization & Sharding',
      'Legacy Codebase Refactoring',
    ],
    technologies: ['Node.js', 'Go', 'React', 'PostgreSQL', 'Docker', 'AWS'],
    benefits: [
      { title: 'De-Risked Migration', description: 'Incremental transition strategies preventing downtime during critical system cutovers.' },
      { title: 'Performance Boost', description: 'Modern cloud infrastructure significantly accelerating query speeds and page response.' },
      { title: 'Reduced Maintenance', description: 'Replacing legacy technical debt with maintainable, well-documented codebases.' },
    ],
  },
  {
    id: 'qa-testing',
    slug: 'qa-testing',
    title: 'QA & Testing',
    eyebrow: 'Quality Assurance',
    description: 'We provide functional, API, integration, automated, performance, and end-to-end testing to improve release quality.',
    longDescription: 'We provide functional, API, integration, automated, performance, and end-to-end testing to improve release quality and catch bugs before they reach production.',
    iconName: 'ShieldCheck',
    features: [
      'Automated E2E Testing (Playwright / Cypress)',
      'Unit & Integration Test Suites (Jest / Vitest)',
      'Load & Stress Testing (k6)',
      'Security & Vulnerability Audits',
    ],
    technologies: ['Playwright', 'Vitest', 'Jest', 'k6', 'SonarQube'],
    benefits: [
      { title: 'Higher Release Confidence', description: 'Automated regression testing ensuring core user workflows remain unbroken.' },
      { title: 'Faster CI Feedback', description: 'Parallel test suites running on every pull request to catch issues early.' },
      { title: 'Production Stability', description: 'Load testing identifying memory leaks and latency bottlenecks prior to launch.' },
    ],
  },
]
