import { ServiceItem } from '@/types/services'

export const SERVICES: ServiceItem[] = [
  {
    id: 'web-development',
    slug: 'web-development',
    title: 'Web Development',
    eyebrow: 'Frontend & Web Platforms',
    category: 'build',
    navDescription: 'Responsive web apps, portals, and dashboards.',
    description: 'We build responsive web applications, customer portals, dashboards, internal tools, SaaS products, and other browser-based systems.',
    longDescription: 'We build responsive web applications, customer portals, dashboards, internal tools, SaaS products, and other browser-based systems designed for speed, security, and seamless user experiences.',
    whoItsFor: 'Best fit for teams launching a new customer-facing product, replacing a slow or outdated web app, or building an internal tool that needs to scale past a spreadsheet.',
    iconName: 'Layout',
    methodologyKey: 'web',
    features: [
      'Responsive Web Applications',
      'Customer Portals & Dashboards',
      'Internal Workflow Tools',
      'SaaS Platforms & Web Systems',
    ],
    technologies: ['React', 'Next.js', 'TypeScript', 'Tailwind CSS', 'Node.js'],
    benefits: [
      { title: 'Sub-Second First Paint', description: 'Optimized server-side rendering and edge caching delivering top performance scores.' },
      { title: 'Modern User Experience', description: 'Intuitive interface patterns that simplify complex workflows for end users.' },
      { title: 'Scalable Architecture', description: 'Modular component architecture built to expand smoothly as your product grows.' },
    ],
    faqs: [
      { question: 'How long does a typical web project take?', answer: 'A focused MVP or internal tool usually takes 6–10 weeks. A full customer-facing platform with multiple user roles typically runs 3–5 months. You get a specific estimate after the discovery phase, not before.' },
      { question: 'Do you work with our existing design system, or build a new one?', answer: 'Both — if you have an existing design system or Figma library, we build against it. If not, we design a component system as part of the first phase so future pages stay consistent.' },
      { question: 'Who owns the code once the project is done?', answer: 'You do, fully. Source code, documentation, and deployment access transfer to you at project close — there\'s no ongoing dependency on us unless you choose a support arrangement.' },
      { question: 'What happens after launch?', answer: 'Every project includes a hypercare period to catch real-world issues. After that, you can move to an ongoing support retainer or take full ownership — your choice.' },
    ],
  },
  {
    id: 'mobile-development',
    slug: 'mobile-development',
    title: 'Mobile Development',
    eyebrow: 'iOS & Android Applications',
    category: 'build',
    navDescription: 'Native and cross-platform iOS & Android apps.',
    description: 'We build mobile applications for iOS and Android, including cross-platform applications when one shared codebase makes sense.',
    longDescription: 'We build mobile applications for iOS and Android, including cross-platform applications when one shared codebase makes sense, pairing native device capabilities with fluid interfaces.',
    whoItsFor: 'Best fit for companies launching a first mobile app, extending a web product to mobile, or needing offline-capable field/frontline apps.',
    iconName: 'Smartphone',
    methodologyKey: 'mobile',
    features: [
      'iOS & Android Applications',
      'Cross-Platform Apps (Flutter / React Native)',
      'Native Swift & Kotlin Modules',
      'Offline-First Local Storage & Sync',
    ],
    technologies: ['Flutter', 'React Native', 'Swift', 'Kotlin', 'Firebase'],
    benefits: [
      { title: 'Smooth 60FPS UI', description: 'Responsive animations and instant touch response across low-end and flagship devices.' },
      { title: 'Offline Reliability', description: 'Local caching and background sync ensuring continuous operation during network drops.' },
      { title: 'Efficient Delivery', description: 'Shared codebase architecture enabling simultaneous iOS and Android releases.' },
    ],
    faqs: [
      { question: 'Should we go native or cross-platform?', answer: 'Depends on the app. If it\'s UI-heavy with platform-specific interactions, native (Swift/Kotlin) is usually worth it. If speed-to-market and one team maintaining both platforms matters more, Flutter or React Native gets you there faster without a real quality trade-off for most apps.' },
      { question: 'Do you handle App Store and Play Store submission?', answer: 'Yes — we manage code signing, store listings, screenshots, and the review process, including phased rollouts so a bad release only affects a small percentage of users first.' },
      { question: 'Can you integrate with our existing backend/APIs?', answer: 'Yes, that\'s the default assumption. We build the mobile client against your existing API contract, or help design one if it doesn\'t exist yet.' },
      { question: 'How do you handle offline functionality?', answer: 'We use local-first storage (SQLite or similar) with background sync and conflict resolution, so the app stays usable on a bad connection and reconciles safely once connectivity returns.' },
    ],
  },
  {
    id: 'backend-api-development',
    slug: 'backend-api-development',
    title: 'Backend & API Development',
    eyebrow: 'Services & Integrations',
    category: 'build',
    navDescription: 'APIs, microservices, and backend systems.',
    description: 'We build APIs, microservices, integrations, authentication systems, business logic, and the backend services that power applications.',
    longDescription: 'We build APIs, microservices, integrations, authentication systems, business logic, and the backend services that power applications with high throughput and low latency.',
    whoItsFor: 'Best fit for teams that already have a frontend (or an outside frontend team) and need a solid backend, or need to connect several existing systems through a clean API layer.',
    iconName: 'Server',
    methodologyKey: 'backend',
    features: [
      'REST & gRPC Microservices',
      'Third-Party Integrations & Webhooks',
      'OAuth2 & Authentication Systems',
      'High-Throughput Data Pipelines',
    ],
    technologies: ['Node.js', 'Go', 'Python', 'PostgreSQL', 'Redis', 'Kafka'],
    benefits: [
      { title: 'Low-Latency Queries', description: 'Optimized database schema design and connection pooling for rapid response times.' },
      { title: 'Resilient Integrations', description: 'Automated retry and circuit-breaker mechanisms preventing third-party cascade failures.' },
      { title: 'Robust Security', description: 'Enterprise authentication, encryption, and granular rate-limiting built in from day one.' },
    ],
    faqs: [
      { question: 'Can you work alongside our existing frontend team?', answer: 'Yes — this is one of our most common engagements. We define a clear API contract up front so your frontend team can build against it without waiting on us, and vice versa.' },
      { question: 'How do you choose between REST and gRPC?', answer: 'REST for most public-facing or partner-facing APIs where broad compatibility matters; gRPC when you need lower latency between internal services or are handling high-throughput streaming data.' },
      { question: 'What if we need to integrate with a legacy or third-party system?', answer: 'This is routine work for us. We wrap legacy or third-party systems behind a clean internal API so the rest of your stack doesn\'t need to know how messy the underlying integration actually is.' },
      { question: 'How do you handle authentication and security?', answer: 'OAuth2/OIDC for standard authentication flows, with rate-limiting and encryption applied from the first deployment — not added later as a patch.' },
    ],
  },
  {
    id: 'enterprise-software',
    slug: 'enterprise-software',
    title: 'Enterprise Software',
    eyebrow: 'Mission-Critical Systems',
    category: 'scale',
    navDescription: 'ERP, financial platforms, and business-critical systems.',
    description: 'We build and improve business-critical systems, internal applications, workflow tools, financial platforms, and system integrations.',
    longDescription: 'We build and improve business-critical systems, internal applications, workflow tools, financial platforms, and system integrations tailored precisely to complex operational logic.',
    whoItsFor: 'Best fit for mid-size to large organizations replacing spreadsheets or an outgrown off-the-shelf tool with a system built around their actual operational workflow.',
    iconName: 'Workflow',
    methodologyKey: 'erp',
    features: [
      'Custom ERP & Resource Architectures',
      'Financial & Transactional Ledgers',
      'Business Workflow Automation',
      'Multi-Tenant Enterprise Portals',
    ],
    technologies: ['PostgreSQL', '.NET', 'Go', 'React', 'Docker', 'Kubernetes'],
    benefits: [
      { title: 'Unified Data Operations', description: 'Single consolidated view across operations, inventory, and financial reporting.' },
      { title: 'Strict Data Integrity', description: 'ACID transactional schemas and comprehensive audit logs protecting critical records.' },
      { title: 'Zero Licensing Lock-In', description: 'Full source code and intellectual property ownership delivered to your organization.' },
    ],
    faqs: [
      { question: 'Should we buy an off-the-shelf ERP or build custom?', answer: 'If a platform like SAP, Dynamics, or Odoo covers 80%+ of your workflow, buying is usually cheaper. Custom makes sense once you\'re paying for heavy customization anyway, or your process genuinely doesn\'t fit any off-the-shelf model.' },
      { question: 'How do you handle migrating data from our current system?', answer: 'Migration gets its own dedicated testing cycle, separate from the main build — this is the step most ERP projects get wrong by rushing it right before go-live.' },
      { question: 'Can this integrate with our existing accounting/CRM software?', answer: 'Yes — we regularly connect new systems to legacy platforms and third-party tools via API, without requiring you to replace everything at once.' },
      { question: 'What does ongoing support look like after launch?', answer: 'A defined hypercare period immediately post-launch, then an ongoing support arrangement if you want it — or full internal ownership with complete documentation if you don\'t.' },
    ],
  },
  {
    id: 'cloud-devops',
    slug: 'cloud-devops',
    title: 'Cloud & DevOps',
    eyebrow: 'Infrastructure & Automation',
    category: 'scale',
    navDescription: 'Infrastructure, CI/CD, and reliable deployments.',
    description: 'We help applications run reliably through cloud infrastructure, containers, CI/CD pipelines, deployment automation, monitoring, and scaling.',
    longDescription: 'We help applications run reliably through cloud infrastructure, containers, CI/CD pipelines, deployment automation, monitoring, and scaling for maximum uptime.',
    whoItsFor: 'Best fit for teams whose deployments are manual and risky, whose infrastructure costs are creeping up unexplained, or who are scaling past what a single server can handle.',
    iconName: 'Cloud',
    methodologyKey: 'cloud',
    features: [
      'Infrastructure as Code (Terraform)',
      'Kubernetes & Container Orchestration',
      'Automated CI/CD Release Pipelines',
      'Monitoring, Alerting & SRE Dashboards',
    ],
    technologies: ['AWS', 'GCP', 'Docker', 'Kubernetes', 'Terraform', 'Prometheus'],
    benefits: [
      { title: 'Zero-Downtime Releases', description: 'Automated blue/green and canary deployment pipelines with instant rollback triggers.' },
      { title: 'High Availability', description: 'Multi-zone redundancy and auto-scaling accommodating unexpected traffic surges.' },
      { title: 'Cost Optimization', description: 'Efficient cloud resource provisioning reducing unnecessary infrastructure overhead.' },
    ],
    faqs: [
      { question: 'Do you work with our existing cloud provider?', answer: 'Yes — we work across AWS, GCP, and Azure. We\'ll recommend a provider if you\'re starting fresh, but won\'t push a migration you don\'t need.' },
      { question: 'Can you take over an existing, undocumented infrastructure setup?', answer: 'Yes, this is common. We start with an infrastructure audit to document what actually exists before making changes — no changes go in blind.' },
      { question: 'How do you reduce cloud costs without hurting performance?', answer: 'Usually through right-sizing over-provisioned resources, adding auto-scaling so you\'re not paying for peak capacity 24/7, and cleaning up orphaned resources — audited and reported before any changes are made.' },
      { question: 'What happens if a deployment fails?', answer: 'Automated rollback triggers on error-rate spikes, so a bad deploy self-corrects within minutes rather than requiring a manual, middle-of-the-night fix.' },
    ],
  },
  {
    id: 'ai-automation',
    slug: 'ai-automation',
    title: 'AI & Automation',
    eyebrow: 'Intelligent Workflows',
    category: 'elevate',
    navDescription: 'AI assistants, automation, and LLM integrations.',
    description: 'We use AI and automation where they solve a real problem, including intelligent assistants, workflow automation, data processing, and AI integrations.',
    longDescription: 'We use AI and automation where they solve a real problem, including intelligent assistants, workflow automation, data processing, and AI integrations that eliminate manual bottlenecks.',
    whoItsFor: 'Best fit for teams drowning in a specific repetitive task (document processing, support triage, data entry) where automation has a clear, bounded scope — not for "add AI everywhere" projects.',
    iconName: 'Sparkles',
    methodologyKey: 'ai',
    features: [
      'Intelligent Assistants & Chatbots',
      'Automated Document Processing (OCR)',
      'Workflow & RPA Automation',
      'Custom LLM & API Integrations',
    ],
    technologies: ['Python', 'LangChain', 'OpenAI', 'FastAPI', 'PostgreSQL'],
    benefits: [
      { title: 'Automated Data Extraction', description: 'High-accuracy parsing of invoices, receipts, and unstructured documents.' },
      { title: 'Operational Efficiency', description: 'Eliminating hundreds of hours of repetitive manual data entry tasks.' },
      { title: 'Practical Integration', description: 'Targeted AI models solving concrete business problems with measurable ROI.' },
    ],
    faqs: [
      { question: 'How do you decide if a task is actually a good fit for AI?', answer: 'We look for tasks that are repetitive, rule-describable, and currently done manually — document processing and structured data extraction are strong fits. Open-ended decision-making usually isn\'t, and we\'ll tell you honestly if that\'s the case.' },
      { question: 'What about accuracy and hallucination risk?', answer: 'We design for human-in-the-loop review on anything with real consequences, and validate accuracy against your actual documents/data before going live — not just a generic benchmark.' },
      { question: 'Do you build on top of existing models or train custom ones?', answer: 'Almost always the former — fine-tuning or training a custom model is rarely worth the cost compared to well-engineered prompting and retrieval against an existing model like GPT-4 class models.' },
      { question: 'How is this different from generic RPA tools?', answer: 'Off-the-shelf RPA tools break when a form layout changes slightly. We build automation that handles that kind of real-world variability, because it\'s actually understanding content, not just clicking fixed coordinates.' },
    ],
  },
  {
    id: 'software-modernization',
    slug: 'software-modernization',
    title: 'Software Modernization',
    eyebrow: 'Architecture & Migration',
    category: 'scale',
    navDescription: 'Migrate and modernize legacy applications.',
    description: 'We help modernize older applications by improving architecture, moving workloads to the cloud, introducing APIs or microservices, and replacing outdated technology.',
    longDescription: 'We help modernize older applications by improving architecture, moving workloads to the cloud, introducing APIs or microservices, and replacing outdated technology safely without disrupting operations.',
    whoItsFor: 'Best fit for companies running a system that works but is slow to change, hard to hire for, or sitting on infrastructure that\'s becoming a liability (end-of-life servers, unsupported frameworks).',
    iconName: 'GitMerge',
    methodologyKey: 'modernization',
    features: [
      'Monolith to Microservices Transition',
      'Cloud Migration & Containerization',
      'Database Optimization & Sharding',
      'Legacy Codebase Refactoring',
    ],
    technologies: ['Node.js', 'Go', 'React', 'PostgreSQL', 'Docker', 'AWS'],
    benefits: [
      { title: 'De-Risked Migration', description: 'Incremental transition strategies preventing downtime during critical system cutovers.' },
      { title: 'Performance Boost', description: 'Modern cloud infrastructure significantly accelerating query speeds and page response.' },
      { title: 'Reduced Maintenance', description: 'Replacing legacy technical debt with maintainable, well-documented codebases.' },
    ],
    faqs: [
      { question: 'Do we have to stop using the old system during migration?', answer: 'No — we default to incremental, phased migration (the strangler-fig pattern) so the old system keeps running while new pieces take over gradually. A full-stop rewrite is rarely the right call.' },
      { question: 'How do you avoid breaking things that currently work?', answer: 'We treat existing behavior as a specification, even undocumented parts — building a test suite against current behavior before changing anything, so regressions get caught immediately.' },
      { question: 'How long does a modernization project take?', answer: 'Highly dependent on scope — a single service extraction might take 4–6 weeks, while a full monolith-to-microservices transition can run 6–12 months. We scope in phases so you see value incrementally, not just at the very end.' },
      { question: 'What if our current codebase has no documentation?', answer: 'That\'s the normal starting point, not an obstacle. Part of the discovery phase is reverse-engineering the system\'s actual behavior directly from the code and its running state.' },
    ],
  },
  {
    id: 'qa-testing',
    slug: 'qa-testing',
    title: 'QA & Testing',
    eyebrow: 'Quality Assurance',
    category: 'elevate',
    navDescription: 'Automated testing and release quality assurance.',
    description: 'We provide functional, API, integration, automated, performance, and end-to-end testing to improve release quality.',
    longDescription: 'We provide functional, API, integration, automated, performance, and end-to-end testing to improve release quality and catch bugs before they reach production.',
    whoItsFor: 'Best fit for teams shipping frequently without a reliable safety net, or preparing for a high-stakes release (compliance audit, peak sales event) where manual testing alone is too slow or too risky.',
    iconName: 'ShieldCheck',
    methodologyKey: 'qa',
    features: [
      'Automated E2E Testing (Playwright / Cypress)',
      'Unit & Integration Test Suites (Jest / Vitest)',
      'Load & Stress Testing (k6)',
      'Security & Vulnerability Audits',
    ],
    technologies: ['Playwright', 'Vitest', 'Jest', 'k6', 'SonarQube'],
    benefits: [
      { title: 'Higher Release Confidence', description: 'Automated regression testing ensuring core user workflows remain unbroken.' },
      { title: 'Faster CI Feedback', description: 'Parallel test suites running on every pull request to catch issues early.' },
      { title: 'Production Stability', description: 'Load testing identifying memory leaks and latency bottlenecks prior to launch.' },
    ],
    faqs: [
      { question: 'Can you test our existing application, or only ones you build?', answer: 'We regularly bring testing to applications we didn\'t build — the first step is always understanding the existing critical user flows before writing any test suite.' },
      { question: 'How much of this can actually be automated vs. needs manual testing?', answer: 'Most repeatable functional flows should be automated; manual testing stays valuable for exploratory testing and genuinely subjective UX judgment. We\'ll tell you honestly which is which rather than over-automating for its own sake.' },
      { question: 'Do you test mobile apps as well as web?', answer: 'Yes — the same principles apply, using device-farm testing across a real spread of OS versions and screen sizes rather than just a simulator.' },
      { question: 'What does a load-testing engagement actually involve?', answer: 'We simulate realistic and peak traffic patterns against a staging environment, identify where the system actually breaks (not just where it slows down), and give you a concrete capacity report before your real peak event.' },
    ],
  },
]